### ISSUE TITLE
how to obfuscate html

### ISSUE THREAD

**Issue by frmdeveloper** [javascript-obfuscator/javascript-obfuscator#1033]
my code
```js
const obfuscate = (kodeJS, optionn = {}) => {
     var obfuscationResult = JavaScriptObfuscator.obfuscate(kodeJS, {
        compact: false,
        controlFlowFlattening: true,
        controlFlowFlatteningThreshold: 1,
        numbersToExpressions: true,
        simplify: true,
        stringArrayShuffle: true,
        splitStrings: true,
        stringArrayThreshold: 1,
        ...optionn
     })
     return obfuscationResult.getObfuscatedCode()
}

var html = fs.readFileSync('./assets/index.html')+''
return obfuscate(`document.write("${html}")`)
```
I get an error log like this
```
Error: ERROR at line 1: Unterminated string constant (1:15)
> ...document.write("<!DOCTYPE html...
    at Function.processParsingError (/root/frmdev/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/ASTParserFacade.ts:73:15)
    at Function.parse (/root/frmdev/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/ASTParserFacade.ts:39:49)
    at o.parseCode (/root/frmdev/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/JavaScriptObfuscator.ts:82:50)
    at obfuscate (/root/frmdev/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/JavaScriptObfuscator.ts:73:30)
    at Function.obfuscate (/root/frmdev/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/JavaScriptObfuscatorFacade.ts:16:56)
    at obfuscate (/root/frmdev/lib/functions.js:232:47)
    at eval (eval at exports.chatupdate (/root/frmdev/index.js:3097:25), <anonymous>:2:8)
    at eval (eval at exports.chatupdate (/root/frmdev/index.js:3097:25), <anonymous>:2:49)
    at Object.exports.chatupdate (/root/frmdev/index.js:3097:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by da411d** [comment]
javascript-obfuscator is javascript obfuscator, not html-obfuscator. Even not jsx obfuscator.

**Comment by frmdeveloper** [comment]
> javascript-obfuscator is javascript obfuscator, not html-obfuscator. Even not jsx obfuscator.

document.write it includes javascript

**Comment by horvathlaszlogyorgy** [comment]
**You can obfuscate only JS code**, so you can not able to obfuscate some JS code that mixed with HTML code. For example, you can not obfuscate this code:

```html
<!DOCTYPE html>
<html>
	<head>
	<title>Title of the document</title>
	</head>
	<body>
		<p id="paragraph">Default value</p>
		<script type="text/javascript">
			document.querySelector("#paragraph").innerText = "Modified value";
		</script>
	</body>
</html>
```

But you can obfuscate this part of the code:
```js
document.querySelector("#paragraph").innerText = "Modified value";
```

... and you can insert obfuscated code back to HTML.

You can even make this process automatic by using HTML tools

**Comment by da411d** [comment]
Okay, i misunderstood you. Soo, you obfuscate code in the way below:
```
var html = fs.readFileSync('./assets/index.html')+''
return obfuscate(`document.write("${html}")`)
```

Then the content of argument for `obfuscate` will be:
```
document.write("<!DOCTYPE html>
<html>
  <head>
  <meta name="name" value="value">")
```

So, in this case, the generated javascript code is not valid: string literals cannot have linebreaks in tha way and quotes are braking string literal.

So you need at least escape quotes and linebreak.

Also you can encode the code with `escape`.
```
return obfuscate(`document.write(unescape("${escape(html)}"))`)
```

Then the code generated will look like this:
```
document.write(unescape('%3C%21DOCTYPE%20html%3E%0A%3Chtml%3E%0A%20%20%3Chead%3E%0A%20%20%3Cmeta%20name%3D%22name%22%20value%3D%22value%22%3E'))
```

**Comment by frmdeveloper** [comment]
Thanks
