### ISSUE TITLE
obfuscate with unicode characters like 䮾, 鸗, 䰱, 䪊

### ISSUE THREAD

**Issue by the-eric-kwok** [javascript-obfuscator/javascript-obfuscator#1074]
**Is your feature request related to a problem? Please describe.**
This is not necessary but fun to obfuscate all variable with unicode characters. Now if I use emoji as dictionary and pass it to `--identifiers-dictionary`, the obfuscator will throw error:
```
/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/generators/identifier-names-generators/DictionaryIdentifierNamesGenerator.ts:84
                throw new Error('Too many identifiers in the code, add more words to identifiers dictionary');
                      ^
Error: Too many identifiers in the code, add more words to identifiers dictionary
    at generateNewDictionaryName (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/generators/identifier-names-generators/DictionaryIdentifierNamesGenerator.ts:84:23)
    at generateNewDictionaryName (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/generators/identifier-names-generators/DictionaryIdentifierNamesGenerator.ts:97:20)
    at o.generateNewDictionaryName (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/generators/identifier-names-generators/DictionaryIdentifierNamesGenerator.ts:99:16)
    at o.generateForLexicalScope (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/generators/identifier-names-generators/DictionaryIdentifierNamesGenerator.ts:73:37)
    at g.storeLocalName (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/node-transformers/rename-identifiers-transformers/replacer/IdentifierReplacer.ts:50:65)
    at N.storeIdentifierName (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/node-transformers/dead-code-injection-transformers/DeadCodeInjectionIdentifiersTransformer.ts:62:33)
    at N.transformScopeThroughIdentifiers (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/node-transformers/dead-code-injection-transformers/DeadCodeInjectionIdentifiersTransformer.ts:58:14)
    at callback (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/node-transformers/dead-code-injection-transformers/DeadCodeInjectionIdentifiersTransformer.ts:49:18)
    at o.traverseScopeThroughIdentifiersRecursive (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/node/ScopeIdentifiersTraverser.ts:76:13)
    at o.traverseScopeThroughIdentifiersRecursive (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/node/ScopeIdentifiersTraverser.ts:83:18)
```

**Describe the solution you'd like**
Support passing unicode characters to `--identifiers-dictionary`

----------------
Update: sorry I thought use emoji as variable name is supported.

**Comment by the-eric-kwok** [comment]
I'm running in CLI mode with this command:
```
javascript-obfuscator xxx.js \
--compact true \
--unicode-escape-sequence true \
--dead-code-injection true \
--split-strings true \
--split-strings-chunk-length 5 \
--simplify true \
--rename-globals true \
--identifier-names-generator dictionary \
--identifiers-dictionary 䰱䰱䰱䰱䰱䰱䰱䰱,䰱䰱䰱䰱䰱䰱䰱䮾,䰱䰱䰱䰱䰱䰱䮾䰱,䰱䰱䰱䰱䰱䰱䮾䮾,䰱䰱䰱䰱䰱䮾䰱䰱,䰱䰱䰱䰱䰱䮾䰱䮾,䰱䰱䰱䰱䰱䮾䮾䰱,䰱䰱䰱䰱䰱䮾䮾䮾,䰱䰱䰱䰱䮾䰱䰱䰱,䰱䰱䰱䰱䮾䰱䰱䮾,䰱䰱䰱䰱䮾䰱䮾䰱,䰱䰱䰱䰱䮾䰱䮾䮾,䰱䰱䰱䰱䮾䮾䰱䰱,䰱䰱䰱䰱䮾䮾䰱䮾,䰱䰱䰱䰱䮾䮾䮾䰱,䰱䰱䰱䰱䮾䮾䮾䮾,䰱䰱䰱䮾䰱䰱䰱䰱,䰱䰱䰱䮾䰱䰱䰱䮾,䰱䰱䰱䮾䰱䰱䮾䰱,䰱䰱䰱䮾䰱䰱䮾䮾,䰱䰱䰱䮾䰱䮾䰱䰱,䰱䰱䰱䮾䰱䮾䰱䮾,䰱䰱䰱䮾䰱䮾䮾䰱,䰱䰱䰱䮾䰱䮾䮾䮾,䰱䰱䰱䮾䮾䰱䰱䰱,䰱䰱䰱䮾䮾䰱䰱䮾,䰱䰱䰱䮾䮾䰱䮾䰱,䰱䰱䰱䮾䮾䰱䮾䮾,䰱䰱䰱䮾䮾䮾䰱䰱,䰱䰱䰱䮾䮾䮾䰱䮾,䰱䰱䰱䮾䮾䮾䮾䰱,䰱䰱䰱䮾䮾䮾䮾䮾,䰱䰱䮾䰱䰱䰱䰱䰱,䰱䰱䮾䰱䰱䰱䰱䮾,䰱䰱䮾䰱䰱䰱䮾䰱,䰱䰱䮾䰱䰱䰱䮾䮾,䰱䰱䮾䰱䰱䮾䰱䰱,䰱䰱䮾䰱䰱䮾䰱䮾,䰱䰱䮾䰱䰱䮾䮾䰱,䰱䰱䮾䰱䰱䮾䮾䮾,䰱䰱䮾䰱䮾䰱䰱䰱,䰱䰱䮾䰱䮾䰱䰱䮾,䰱䰱䮾䰱䮾䰱䮾䰱,䰱䰱䮾䰱䮾䰱䮾䮾,䰱䰱䮾䰱䮾䮾䰱䰱,䰱䰱䮾䰱䮾䮾䰱䮾,䰱䰱䮾䰱䮾䮾䮾䰱,䰱䰱䮾䰱䮾䮾䮾䮾,䰱䰱䮾䮾䰱䰱䰱䰱,䰱䰱䮾䮾䰱䰱䰱䮾,䰱䰱䮾䮾䰱䰱䮾䰱,䰱䰱䮾䮾䰱䰱䮾䮾,䰱䰱䮾䮾䰱䮾䰱䰱,䰱䰱䮾䮾䰱䮾䰱䮾,䰱䰱䮾䮾䰱䮾䮾䰱,䰱䰱䮾䮾䰱䮾䮾䮾,䰱䰱䮾䮾䮾䰱䰱䰱,䰱䰱䮾䮾䮾䰱䰱䮾,䰱䰱䮾䮾䮾䰱䮾䰱,䰱䰱䮾䮾䮾䰱䮾䮾,䰱䰱䮾䮾䮾䮾䰱䰱,䰱䰱䮾䮾䮾䮾䰱䮾,䰱䰱䮾䮾䮾䮾䮾䰱,鸗鸗鸗鸗鸗鸗鸗鸗,鸗鸗鸗鸗鸗鸗鸗聾,鸗鸗鸗鸗鸗鸗聾鸗,鸗鸗鸗鸗鸗鸗聾聾,鸗鸗鸗鸗鸗聾鸗鸗,鸗鸗鸗鸗鸗聾鸗聾,鸗鸗鸗鸗鸗聾聾鸗,鸗鸗鸗鸗鸗聾聾聾,鸗鸗鸗鸗聾鸗鸗鸗,鸗鸗鸗鸗聾鸗鸗聾,鸗鸗鸗鸗聾鸗聾鸗,鸗鸗鸗鸗聾鸗聾聾,鸗鸗鸗鸗聾聾鸗鸗,鸗鸗鸗鸗聾聾鸗聾,鸗鸗鸗鸗聾聾聾鸗,鸗鸗鸗鸗聾聾聾聾,鸗鸗鸗聾鸗鸗鸗鸗,鸗鸗鸗聾鸗鸗鸗聾,鸗鸗鸗聾鸗鸗聾鸗,鸗鸗鸗聾鸗鸗聾聾,鸗鸗鸗聾鸗聾鸗鸗,鸗鸗鸗聾鸗聾鸗聾,鸗鸗鸗聾鸗聾聾鸗,鸗鸗鸗聾鸗聾聾聾,鸗鸗鸗聾聾鸗鸗鸗,鸗鸗鸗聾聾鸗鸗聾,鸗鸗鸗聾聾鸗聾鸗,鸗鸗鸗聾聾鸗聾聾,鸗鸗鸗聾聾聾鸗鸗,鸗鸗鸗聾聾聾鸗聾,鸗鸗鸗聾聾聾聾鸗,鸗鸗鸗聾聾聾聾聾,鸗鸗聾鸗鸗鸗鸗鸗,鸗鸗聾鸗鸗鸗鸗聾,鸗鸗聾鸗鸗鸗聾鸗,鸗鸗聾鸗鸗鸗聾聾,鸗鸗聾鸗鸗聾鸗鸗,鸗鸗聾鸗鸗聾鸗聾,鸗鸗聾鸗鸗聾聾鸗,鸗鸗聾鸗鸗聾聾聾,鸗鸗聾鸗聾鸗鸗鸗,鸗鸗聾鸗聾鸗鸗聾,鸗鸗聾鸗聾鸗聾鸗,鸗鸗聾鸗聾鸗聾聾,鸗鸗聾鸗聾聾鸗鸗,鸗鸗聾鸗聾聾鸗聾,鸗鸗聾鸗聾聾聾鸗,鸗鸗聾鸗聾聾聾聾,鸗鸗聾聾鸗鸗鸗鸗,鸗鸗聾聾鸗鸗鸗聾,鸗鸗聾聾鸗鸗聾鸗,鸗鸗聾聾鸗鸗聾聾,鸗鸗聾聾鸗聾鸗鸗,鸗鸗聾聾鸗聾鸗聾,鸗鸗聾聾鸗聾聾鸗,鸗鸗聾聾鸗聾聾聾,鸗鸗聾聾聾鸗鸗鸗,鸗鸗聾聾聾鸗鸗聾,鸗鸗聾聾聾鸗聾鸗,鸗鸗聾聾聾鸗聾聾,鸗鸗聾聾聾聾鸗鸗,鸗鸗聾聾聾聾鸗聾,鸗鸗聾聾聾聾聾鸗
```
