### ISSUE TITLE
javascript-obfuscator 3.0.1 introduced an incompatibility through inversify@6.0.1

### ISSUE THREAD

**Issue by l9c** [javascript-obfuscator/javascript-obfuscator#1081]
TypeError raised on JavaScriptObfuscator.obfuscate
## Current Behavior

TypeError: [].values is not a function
    at _getContainerActivationsForService (/appbuild/project_root/node_modules/inversify/src/resolution/resolver.ts:203:99)
    at _onActivation (/appbuild/project_root/node_modules/inversify/src/resolution/resolver.ts:133:33)
    at /appbuild/project_root/node_modules/inversify/src/resolution/resolver.ts:115:16
    at _resolveInScope (/appbuild/project_root/node_modules/inversify/src/resolution/resolver.ts:100:12)
    at _resolveBinding (/appbuild/project_root/node_modules/inversify/src/resolution/resolver.ts:110:10)
    at /appbuild/project_root/node_modules/inversify/src/resolution/resolver.ts:41:14
    at childRequests.reduce.constructorInjections (/appbuild/project_root/node_modules/inversify/src/resolution/instantiation.ts:27:23)
    at Array.reduce (<anonymous>)
    at _resolveRequests (/appbuild/project_root/node_modules/inversify/src/resolution/instantiation.ts:26:24)
    at _createInstance (/appbuild/project_root/node_modules/inversify/src/resolution/instantiation.ts:50:22)

## Steps to Reproduce

My test.js:
```
var JavaScriptObfuscator = require('javascript-obfuscator');
console.log(JavaScriptObfuscator.version);

var obfuscationResult = JavaScriptObfuscator.obfuscate('', {
  compact: false,
  controlFlowFlattening: true,
  controlFlowFlatteningThreshold: 1,
  numbersToExpressions: true,
  simplify: true,
  stringArrayShuffle: true,
  splitStrings: true,
  stringArrayThreshold: 1
});

```
node test.js

## Your Environment

* Obfuscator version used: 3.0.1
* Node version used: v8.17.0 (npm v6.7.0)

**Comment by jcrespoven** [comment]
The same is happening to me just when executing javascript-obfuscator from a gitlab-runner. It was not happening in version 3.0.0
