### ISSUE TITLE
Help! Cannot find module 'color-convert'

### ISSUE THREAD

**Issue by djunique** [javascript-obfuscator/javascript-obfuscator#111]
Hi, I followed the install instructions and when I run a command I'm getting the following error:

Error: Cannot find module 'color-convert'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/javascript-obfuscator/node_modules/ansi-styles/index.js:2:22)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)

I've tried a number of things but I can't get it to work.

**Comment by sanex3339** [comment]
How did you install this package?

**Comment by djunique** [comment]
Sorry, this is the processes:

npm install --save-dev javascript-obfuscator

I've tried removing node_modules and I've run npm i

No luck :(

**Comment by sanex3339** [comment]
Cannot reproduce. Clear instal on my mac not triggered this error. And all tests on Travis CI are passed.

https://travis-ci.org/javascript-obfuscator/javascript-obfuscator/builds/277295811

**Comment by sanex3339** [comment]
Ping

**Comment by djunique** [comment]
I've managed to fix the problem. Because on a MacBook you have to use npm link, there was a permission issue in /usr/local/lib/node_modules

Changing the permission on that folder fixed the issue for me.
