### ISSUE TITLE
javascript-obfuscator/test/index.spec.ts:1 import 'reflect-metadata'; SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by macoomac** [javascript-obfuscator/javascript-obfuscator#1253]
## Steps to Reproduce

1.git clone https://github.com/javascript-obfuscator/javascript-obfuscator.git
2.npm install --save-dev javascript-obfuscator
3.npm run build
4.ob/javascript-obfuscator/test/index.spec.ts:1
import 'reflect-metadata';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1187:20)
    at Module._compile (node:internal/modules/cjs/loader:1231:27)
    at Module.replacementCompile (/work/jsdync/ob/javascript-obfuscator/node_modules/append-transform/index.js:60:13)
    at module.exports (/work/jsdync/ob/javascript-obfuscator/node_modules/default-require-extensions/js.js:7:9)
    at Object.<anonymous> (/work/jsdync/ob/javascript-obfuscator/node_modules/append-transform/index.js:64:4)
    at Module.load (node:internal/modules/cjs/loader:1125:32)
    at Function.Module._load (node:internal/modules/cjs/loader:965:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
error Command failed with exit code 1.

## Your Environment

* Obfuscator version used:
* Node version used:

# Stack trace

**Comment by macoomac** [comment]
Your Environment
Obfuscator version used:  4.1.0
Node version used:    v20.0.0

**Comment by sanex3339** [comment]
Will release a new version today with the fix

**Comment by sanex3339** [comment]
Released
