### ISSUE TITLE
'super' (es2015) not supported

### ISSUE THREAD

**Issue by malafaya** [javascript-obfuscator/javascript-obfuscator#126]
```
class DerivedClass extends BaseClass {
  constructor() {
    super();

    console.log('Hello, World, from Derived Class!');
  }
}
```

----

```
C:\Workspace\node_modules\escope\node_modules\estraverse\estraverse.js:511
                        throw new Error('Unknown node type ' + nodeType + '.');
                              ^
Error: Unknown node type Super.
    at Controller.traverse (C:\Workspace\node_modules\escope\node_modules\estraverse\estraverse.js:511:31)
    at Object.traverse (C:\Workspace\node_modules\escope\node_modules\estraverse\estraverse.js:703:27)
    at Object.analyze (C:\Workspace\node_modules\escope\escope.js:855:20)
    at Object.mangle (C:\Workspace\node_modules\esshorten\lib\esshorten.js:275:26)
    at e.value (C:\Workspace\node_modules\javascript-obfuscator\dist\webpack:\src\JavaScriptObfuscator.ts:274:38)
    at e.value (C:\Workspace\node_modules\javascript-obfuscator\dist\webpack:\src\JavaScriptObfuscator.ts:171:68)
    at Function.value (C:\Workspace\node_modules\javascript-obfuscator\dist\webpack:\src\JavaScriptObfuscatorFacade.ts:27:85)
    at C:\Workspace\_tool_obfuscate.js:43:54
    at tryToString (fs.js:513:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:501:12)
```

**Comment by sanex3339** [comment]
Try disable `mangle` option

**Comment by sanex3339** [comment]
See https://github.com/javascript-obfuscator/javascript-obfuscator/issues/110

**Comment by malafaya** [comment]
true. sorry.
