### ISSUE TITLE
not work for "\\\\"

### ISSUE THREAD

**Issue by felixlutq** [javascript-obfuscator/javascript-obfuscator#1282]
## Steps to Reproduce

1. run "npm install --save-dev javascript-obfuscator" install the obfuscator
2. create a.js with the code can be find at 
3. run the a.js
4. error

## Your Environment

* Obfuscator version used: 10.2.4
* Node version used: 21.3.0

# Stack trace

ode_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\ASTParserFacade.ts:77
        throw new Error(`ERROR at line ${position.line}: ${errorMessage}\n${formattedPointer} ${formattedCodeSlice}`);
              ^
Error: ERROR at line 2: Unterminated string constant (2:31)
> ...placeAll("\\", "\");...
    at Function.processParsingError (d:\WorkSpace\Web\HomeProject\besthome\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\ASTParserFacade.ts:77:15)
    at Function.parse (d:\WorkSpace\Web\HomeProject\besthome\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\ASTParserFacade.ts:43:49)
    at o.parseCode (d:\WorkSpace\Web\HomeProject\besthome\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\JavaScriptObfuscator.ts:87:50)
    at obfuscate (d:\WorkSpace\Web\HomeProject\besthome\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\JavaScriptObfuscator.ts:78:30)
    at Function.obfuscate (d:\WorkSpace\Web\HomeProject\besthome\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\JavaScriptObfuscatorFacade.ts:16:56)
    at Object.<anonymous> (d:\WorkSpace\Web\HomeProject\besthome\src\main\resources\static_dev\scripts\ob.js:9:46)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
## Minimal working example that will help to reproduce issue

var JavaScriptObfuscator = require('javascript-obfuscator');

var content = `
    var a = 'abcd';
    var b = a.replaceAll("\\\\", "\\");
`;

var obfuscationResult = JavaScriptObfuscator.obfuscate(content,
    {
        compact: false,
        controlFlowFlattening: true,
        controlFlowFlatteningThreshold: 1,
        numbersToExpressions: true,
        simplify: true,
        stringArrayShuffle: true,
        splitStrings: true,
        stringArrayThreshold: 1
    }
);

console.log(obfuscationResult.getObfuscatedCode());

**Comment by sanex3339** [comment]
Can't reproduce
