### ISSUE TITLE
Obfuscating Breaks when using `controlFlowFlattening` on optional callback functions.

### ISSUE THREAD

**Issue by smell-of-curry** [javascript-obfuscator/javascript-obfuscator#1298]
## Current Behavior
When using `controlFlowFlattening` on an optional function parameter, the execution breaks instead of running a `.?` callback. A `TypeError: _0x4f6992 is not a function` error. This means it's calling the function even though the execution is optional.

## Steps to Reproduce
1. Download and try code below, you should get a type error.
```ts
import * as esbuild from "esbuild";
import * as JavaScriptObfuscator from "javascript-obfuscator";

const code = `
function executionBreaksOfUndefinedOptionalImport(
  optionalCallback?: () => void
) {
  console.log('I work');
  optionalCallback?.();
  console.log('I work too');
}

console.log('Testing with no optional callback');
executionBreaksOfUndefinedOptionalImport();

console.log('Testing with optional callback');
executionBreaksOfUndefinedOptionalImport(() => {
  console.log('I am optional');
});
`;

(async () => {
  const jsResult = await esbuild.transform(code, {
    loader: "ts",
    sourcemap: false,
    minify: true,
    legalComments: "none",
  });

  console.log(`Pre Obfuscated Code: ${jsResult.code}`);
  eval(jsResult.code);

  const obfuscatedCode = JavaScriptObfuscator.obfuscate(jsResult.code, {
    controlFlowFlattening: true,
    controlFlowFlatteningThreshold: 1,
  }).getObfuscatedCode();

  console.log(`Obfuscated Code: ${obfuscatedCode}`);
  eval(obfuscatedCode);
})();
```
2. Disable `controlFlowFlattening`, and watch how it works fine.

## Your Environment

* Obfuscator version used: 4.1.1
* Node version used: 22.12.0
* Esbuild Version Used: 0.15.18

# Stack trace
```
TypeError: _0x4f6992 is not a function
    at Object.bldMI (eval at <anonymous> (test.ts:39:3), <anonymous>:1:1188)     
    at executionBreaksOfUndefinedOptionalImport (eval at <anonymous> (test.ts:39:3), <anonymous>:1:1303)
    at eval (eval at <anonymous> (test.ts:39:3), <anonymous>:1:1623)
    at test.ts:39:3
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
```

**Comment by smell-of-curry** [comment]
The issue is not a failure of esbuild, I even tried it with normal javascript, but I used esbuild in this example to show a use case of typescript.

**Comment by j4k0xb** [comment]
duplicate: https://github.com/javascript-obfuscator/javascript-obfuscator/issues/1277

**Comment by sanex3339** [comment]
Will be fixed in the next release
