### ISSUE TITLE
esprima.js ErrorHandler.constructError

### ISSUE THREAD

**Issue by StoicaNicusor** [javascript-obfuscator/javascript-obfuscator#138]
I have just installed it on my Win Srv 2008 and I got this error:
```
C:\Users\Administrator\Documents\jsobfuscator\node_modules\esprima\dist\esprima.js:5004
                var error = new Error(msg);
                     ^
Error: Line 1: Unexpected token <
    at ErrorHandler.constructError (C:\Users\Administrator\Documents\jsobfuscator\node_modules\esprima\dist\esprima.js:5004:22)
    at ErrorHandler.createError (C:\Users\Administrator\Documents\jsobfuscator\node_modules\esprima\dist\esprima.js:5020:27)
    at Parser.unexpectedTokenError (C:\Users\Administrator\Documents\jsobfuscator\node_modules\esprima\dist\esprima.js:1985:39)
    at Parser.throwUnexpectedToken (C:\Users\Administrator\Documents\jsobfuscator\node_modules\esprima\dist\esprima.js:1995:21)
    at Parser.parsePrimaryExpression (C:\Users\Administrator\Documents\jsobfuscator\node_modules\esprima\dist\esprima.js:2359:38)
    at Parser.inheritCoverGrammar (C:\Users\Administrator\Documents\jsobfuscator\node_modules\esprima\dist\esprima.js:2278:37)
    at Parser.parseLeftHandSideExpressionAllowCall (C:\Users\Administrator\Documents\jsobfuscator\node_modules\esprima\dist\esprima.js:2892:26)
    at Parser.inheritCoverGrammar (C:\Users\Administrator\Documents\jsobfuscator\node_modules\esprima\dist\esprima.js:2278:37)
    at Parser.parseUpdateExpression (C:\Users\Administrator\Documents\jsobfuscator\node_modules\esprima\dist\esprima.js:2997:26)
    at Parser.parseUnaryExpression (C:\Users\Administrator\Documents\jsobfuscator\node_modules\esprima\dist\esprima.js:3041:26)

C:\Users\Administrator\Documents\jsobfuscator\node_modules\.bin>
```
Any sugestions/ideas ?
I have to say this is my first encounter with nodeJS. Thanks in advance

**Comment by sanex3339** [comment]
Possible your code has error and cannot be parsed by `esprima`. Not related to `javascript-obfuscator`

**Comment by StoicaNicusor** [comment]
@sanex3339 You were right , I was including the <script> & </script> tag. Thanks !
