### ISSUE TITLE
Unexpected token )

### ISSUE THREAD

**Issue by sido420** [javascript-obfuscator/javascript-obfuscator#189]
Getting the following error when I run obfuscator CLI on a directory with compact=true and leaving rest unmentioned.

```
	        var error = new Error(msg);
                     ^
Error: Line 66: Unexpected token )
    at ErrorHandler.constructError (/javascript-obfuscator/node_modules/esprima/dist/esprima.js:5004:22)
    at ErrorHandler.createError (/javascript-obfuscator/node_modules/esprima/dist/esprima.js:5020:27)
    at Parser.unexpectedTokenError (/javascript-obfuscator/node_modules/esprima/dist/esprima.js:1985:39)
    at Parser.throwUnexpectedToken (/javascript-obfuscator/node_modules/esprima/dist/esprima.js:1995:21)
    at Parser.expect (/javascript-obfuscator/node_modules/esprima/dist/esprima.js:2161:19)
    at Parser.expectCommaSeparator (/javascript-obfuscator/node_modules/esprima/dist/esprima.js:2180:19)
    at Parser.parseObjectInitializer (/javascript-obfuscator/node_modules/esprima/dist/esprima.js:2597:23)
    at Parser.inheritCoverGrammar (/javascript-obfuscator/node_modules/esprima/dist/esprima.js:2278:37)
    at Parser.parsePrimaryExpression (/javascript-obfuscator/node_modules/esprima/dist/esprima.js:2347:38)
    at Parser.inheritCoverGrammar (/javascript-obfuscator/node_modules/esprima/dist/esprima.js:2278:37)
```

**Comment by sanex3339** [comment]
Error not related with obfuscator, it's `esprima` error.

Esprima can't parse your javascript, so check your code for a valid js code.

Also you can try to find file that trigger this error and paste it here, i'll check it.

**Comment by sanex3339** [comment]
But from my side, i should catch this errors and output more understandable messages

**Comment by sido420** [comment]
I'm trying to figure out which file might be the culprit. I had to change my dir structure to use JS obfuscator. I'll let you know.

Questions:
Does the tool merge all obfuscated files together too? I dont see an option for that. Its either a single file or directory.
And, unless I missed something merging must be separately done before obfuscation, correct? NOTE: I want to use --self-defending=true.
How would the source maps be dealt with in this scenario? Ideally, I'd like to trace a browser console err back to individual source code file name and line number.

The way I do it using Google compiler is by specifying a list of JS files on the command line and Google compiler generates a single minified file with source map (that actually points to original src files' name and line num (not the minified files line num) like src map should do. Please note that it does both merging and minification itself.

```
--js `cat ${PATH_TO_FILE_WITH_A_LIST_OF_JS_FILES}`
```

**Comment by sanex3339** [comment]
Obfuscator can't combine files into one, use bundlers like webpack for this.
