### ISSUE TITLE
Error: Line 1: Unexpected token 

### ISSUE THREAD

**Issue by ziozec** [javascript-obfuscator/javascript-obfuscator#242]
Hi, i'm receiving this error on linux ubuntu machine instead in local Mac works perfectly.
What can be the issue?

Thanks,
Fabio

/srv/src/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/EspreeFacade.ts:100
        throw new Error(`Line ${position.line}: ${errorMessage}\n${formattedPointer} ${formattedCodeSlice}`);
              ^
Error: Line 1: Unexpected token <
> ...<html>...
    at Function.value (/srv/src/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/EspreeFac
ade.ts:100:15)
    at Function.value (/srv/src/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/EspreeFac
ade.ts:44:65)
    at e.value (/srv/src/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfusc
ator.ts:154:34)
    at e.value (/srv/src/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfusc
ator.ts:135:55)
    at Function.value (/srv/src/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScrip
tObfuscatorFacade.ts:27:85)
    at IncomingMessage.chres.on (/srv/src/app.js:193:66)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)

**Comment by ziozec** [comment]
body is a JS code 

var obfuscationResult = jsObfuscator.obfuscate(
                                body,
                                {
                                    compact: true,
                                    controlFlowFlattening: false,
                                    debugProtection: false,
                                    deadCodeInjection: false,
                                    debugProtectionInterval: false,
                                    disableConsoleOutput: false,
                                    identifierNamesGenerator: 'hexadecimal',
                                    log: false,
                                    renameGlobals: false,
                                    rotateStringArray: true,
                                    selfDefending: true,
                                    stringArray: true,
                                    stringArrayEncoding: false,
                                    stringArrayThreshold: 0.75,
                                    unicodeEscapeSequence: false
                                }
                            );
                            body = obfuscationResult.getObfuscatedCode();

**Comment by sanex3339** [comment]
What version of obfuscator did you install on your `ubuntu` system?

**Comment by ziozec** [comment]
Sorry my issue was related to an wasm file
