### ISSUE TITLE
CLI don't work when is install locally

### ISSUE THREAD

**Issue by bato3** [javascript-obfuscator/javascript-obfuscator#247]
Related to: https://github.com/javascript-obfuscator/javascript-obfuscator/issues/245, https://github.com/javascript-obfuscator/javascript-obfuscator/issues/246

I have shared hosting, and I can't install packages globally. (npm)

And local version try using "my project" `package.json`

**Comment by sanex3339** [comment]
Please, use search. Try to run `npm link` or `npm link javascript-obfuscator`

**Comment by bato3** [comment]
1. I don't have with run command, but after running it program throws error.

2. Do you understated what is sharing hosting? 

```
[czat@s12]:<~/test2>$ npm link javascript-obfuscator
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'\n    at Error (native)',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

```

**Comment by sanex3339** [comment]
So, run it locally with `./node_modules/javascript-obfuscator/bin/javascript-obfiscator`

**Comment by bato3** [comment]
Mesh...

```
$ pwd
/root/test3
$ npm install  --save-dev javascript-obfuscator
$ ./node_modules/javascript-obfuscator/bin/javascript-obfuscator
Error: ENOENT: no such file or directory, open '/root/test3/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at Object.<anonymous> (/root/test3/node_modules/pjson/pjson.js:4:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

```

**Comment by sanex3339** [comment]
Oh, this is bug. Will try to fix it in the near future.

**Comment by rafaelkapela** [comment]
Sabe here...

**Comment by sanex3339** [comment]
Fix in the `master` branch now. You can use version from `master` branch until release.

**Comment by sanex3339** [comment]
0.17.0 version in out!
