### ISSUE TITLE
New error randomly being thrown

### ISSUE THREAD

**Issue by theyezzyman** [javascript-obfuscator/javascript-obfuscator#263]
## Expected Behavior

I use gulp javascript obfuscator to obfuscate my Electron code base. In development I only run "gulp" to avoid obfuscating it every time as it takes a while to do. This was working fine.

## Current Behavior

It stopped working seemingly out of the blue one day. I've rolled back to previous branches and tried, but regardless if I make any changes to the code base before running again it happens. I've tried deleting the min folder each time however it is still produced + throws the error.

## Steps to Reproduce (for bugs)

1. make change to working code base 
2. node gulp (no obfuscation but min folder is still created)
2. launches electron app fine
3. crashes 20 seconds later w/ error

## Your Environment

* Version used:     "gulp-javascript-obfuscator": "^1.1.4"
Electron 2.0.1

# Stack trace

/Users/user/Desktop/destroyer/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/EspreeFacade.ts:100
        throw new Error(`Line ${position.line}: ${errorMessage}\n${formattedPointer} ${formattedCodeSlice}`);
              ^
Error: Line 213: Unexpected token +=
> ...Units.length; += 1) {...
    at Function.value (/Users/user/Desktop/destroyer/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/EspreeFacade.ts:100:15)
    at Function.value (/Users/user/Desktop/destroyer/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/EspreeFacade.ts:44:65)
    at e.value (/Users/user/Desktop/destroyer/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscator.ts:154:34)
    at e.value (/Users/user/Desktop/destroyer/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscator.ts:135:55)
    at Function.value (/Users/user/Desktop/destroyer/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscatorFacade.ts:27:85)
    at DestroyableTransform._transform (/Users/user/Desktop/destroyer/node_modules/gulp-javascript-obfuscator/index.js:19:46)
    at DestroyableTransform.Transform._read (/Users/user/Desktop/destroyer/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/user/Desktop/destroyer/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Users/user/Desktop/destroyer/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/user/Desktop/destroyer/node_modules/readable-stream/lib/_stream_writable.js:417:5)

**Comment by sanex3339** [comment]
Error here:
`Units.length; += 1`

Why there is semicolon before `+=`?

**Comment by sanex3339** [comment]
Looks like this problem is not related with obfuscator. Check this expression
```
for (let i = 0; i < myArr.length; i += 1) { }
```

here: https://obfuscator.io/

This code will obfuscated fine.

**Comment by theyezzyman** [comment]
Thanks for the quick replies.

The error is thrown if I use the obfuscator, but if I comment out the files, it's not thrown. Are you sure that this isn't related to the obfuscator?

**Comment by sanex3339** [comment]
Try to obfuscate whole file with https://obfuscator.io/ 
Error will happen?

From my side it looks like error from different side - gulp, cache or something other.

**Comment by theyezzyman** [comment]
How would I clear cache, thanks

**Comment by sanex3339** [comment]
I mean babel cache or cache of other library.

**Comment by sanex3339** [comment]
Ping. Did you found a problem?

**Comment by sanex3339** [comment]
Closed as inactive. Please, reopen new issue if you will have additional info.
