### ISSUE TITLE
NodeJS : SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by Chorogon** [javascript-obfuscator/javascript-obfuscator#285]
I'm trying to make a telegram bot.

And I am faced with this problem.

This is the code I wrote after looking at the tutorial.

```
class Bot{
    
    init(TOKEN){  
      return new Promise((resolve, reject) => {
      let url = `https://api.telegram.org/bot${TOKEN}/getMe`
      request(url, (error, r, body) => {
        const response = JSON.parse(body).result
        if(error) return
        if(!response) return
        this.id = response.id || '3242344'
        this.first_name = response.first_name || 'Lini'
        this.last_name = response.last_name || ''
        this.username = response.username || 'lini_bot'
        this.language_code = response.language_code || ''
        resolve()
      })
    })
    }
    
    getName(){
        if(this.last_name){
            return `${this.first_name} ${this.last_name}`
        }
        else{
          return `${this.first_name}`
        }
    }
    introduceYourself(){
        console.log(`Hello, my name is ${this.getName()}. You can talk to me through my username: @${this.username}`);
    }

}

class Nob{
    
    const b=new Bot()
    b.init('<qwerasdfzxcvadsfqweradsf>').then(() => {
      b.introduceYourself()
    })
}
```
and this error occurs when you run it with a "yarn start".
```
  const b=new Bot()
          ^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
error Command failed with exit code 1.
```

What should I do to solve this problem?

**Comment by sanex3339** [comment]
You wrote invalid js code. Remove class Nob and just write
```
const b=new Bot()
    b.init('<qwerasdfzxcvadsfqweradsf>').then(() => {
      b.introduceYourself()
    })
```
