### ISSUE TITLE
Using Webpack throws "Cannot apply @injectable decorator multiple times"

### ISSUE THREAD

**Issue by Stilldabomb** [javascript-obfuscator/javascript-obfuscator#314]
## Expected Behavior

The module should load when being `require`d from a Webpack loader.
## Current Behavior

Fails build
## Steps to Reproduce (for bugs)

1. Use `obfuscator-loader` in a webpack project
2.
3.
4.

## Your Environment

* Version used: 0.17.3

# Stack trace

```
ERROR in ./src/main/index.js
    Module build failed: Error: Cannot apply @injectable decorator multiple times.
        at myapp/node_modules/inversify/lib/annotation/injectable.js:8:19
        at DecorateConstructor (myapp/node_modules/reflect-metadata/Reflect.ts:1202:35)
        at Object.decorate (myapp/node_modules/reflect-metadata/Reflect.ts:742:24)
        at _decorate (myapp/node_modules/inversify/lib/annotation/decorator_utils.js:42:13)
        at Object.decorate (myapp/node_modules/inversify/lib/annotation/decorator_utils.js:55:9)
        at Object.<anonymous> (myapp/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/event-emitters/ObfuscationEventEmitter.ts:7:1)
        at r (myapp/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/webpack/bootstrap:19:1)
        at Object.<anonymous> (myapp/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/container/InversifyContainerFacade.ts:29:1)
        at r (myapp/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/webpack/bootstrap:19:1)
        at Object.<anonymous> (myapp/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscatorFacade.ts:11:1)
        at r (myapp/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/webpack/bootstrap:19:1)
        at Object.<anonymous> (myapp/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/index.ts:3:1)
        at r (myapp/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/webpack/bootstrap:19:1)
        at myapp/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/webpack/bootstrap:83:1
        at Object.<anonymous> (myapp/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/webpack/bootstrap:83:1)
        at Module._compile (internal/modules/cjs/loader.js:702:30)
```
## Minimal working example that will help to reproduce issue

`require('javascript-obfuscator')`

**Comment by sanex3339** [comment]
`Try to import loader`
What loader you using?

Not related with `javascript-obfuscator`.

**Comment by Stilldabomb** [comment]
This is definitely an issue with `javascript-obfuscator`, the issue first came up trying to use `obfuscator-loader` and it did the same thing, this is just a library that I wrote and `npm link`'d that is exactly the same thing just one line. There's also an issue on the other repository about it that's 29 days old: https://github.com/javascript-obfuscator/obfuscator-loader/issues/5
