### ISSUE TITLE
TypeError: n.includes is not a function

### ISSUE THREAD

**Issue by bobbyvinon** [javascript-obfuscator/javascript-obfuscator#316]
Freshly installed javascript-obfuscator not works.
Trying to launch javascript-obfuscator from command line without command line parameters

## Expected Behavior
javascript-obfuscator must be launched without errors.

## Current Behavior
javascript-obfuscator aborts with stack trace attached.

## Steps to Reproduce (for bugs)
just run javascript-obfuscator from command line

## Your Environment
Ubuntu 16.04, with latest updates.

* Version used:
javascript-obfuscator, checkouted from git

# Stack trace
TypeError: n.includes is not a function
    at /usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/decorators/Initializable.ts:80:75
    at Array.forEach (native)
    at /usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/decorators/Initializable.ts:74:22
    at /usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/decorators/Initializable.ts:41:9
    at DecorateProperty (/usr/local/lib/node_modules/javascript-obfuscator/node_modules/reflect-metadata/Reflect.ts:1214:35)
    at Object.decorate (/usr/local/lib/node_modules/javascript-obfuscator/node_modules/reflect-metadata/Reflect.ts:737:24)
    at Object.__decorate (/usr/local/lib/node_modules/javascript-obfuscator/node_modules/tslib/tslib.js:89:96)
    at Object.module.exports.Object.defineProperty.value (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/custom-nodes/console-output-nodes/group/ConsoleOutputCustomNodeGroup.ts:32:5)
    at r (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/webpack/bootstrap:19:1)
    at Object.<anonymous> (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/container/modules/custom-nodes/CustomNodesModule.ts:13:1)

## Minimal working example that will help to reproduce issue
no code

**Comment by sanex3339** [comment]
Try to use version from `master` branch. Your problem will fixed?

**Comment by sanex3339** [comment]
Whats node version did you use?

**Comment by bobbyvinon** [comment]
v4.2.6

**Comment by sanex3339** [comment]
Obfuscator supports node `6.11.5`+
