### ISSUE TITLE
Cannot read property 'type' of undefined when using transformObjectKeys

### ISSUE THREAD

**Issue by Slapbox** [javascript-obfuscator/javascript-obfuscator#318]
## Expected Behavior
Using transformObjectKeys should not cause an error

## Current Behavior
It causes the following error.

## Steps to Reproduce (for bugs)
Unknown

## Your Environment
* Obfuscator version used: Versions 0.14 through 0.18 have had this issue
* Node version used: 8.11.3

The code is generated by Webpack and the Webpack output.libraryTarget is 'commonjs2'

# Stack trace

```
C:\Projects\myApp\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\node\NodeGuards.ts:262
        return node.type === NodeType.ObjectPattern;
                    ^
TypeError: Cannot read property 'type' of undefined
    at Function.type (C:\Projects\myApp\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\node\NodeGuards.ts:262:21)
    at Function.isObjectPatternNode (C:\Projects\myApp\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\node-transformers\converting-transformers\properties-extractors\AbstractPropertiesExtractor.ts:78:27)
    at t.isProhibitedPattern (C:\Projects\myApp\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\node-transformers\converting-transformers\properties-extractors\AbstractPropertiesExtractor.ts:112:45)
    at t.extractPropertiesToExpressionStatements (C:\Projects\myApp\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\node-transformers\converting-transformers\properties-extractors\AbstractPropertiesExtractor.ts:179:14)
    at transformObjectExpressionNode (C:\Projects\myApp\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\node-transformers\converting-transformers\properties-extractors\VariableDeclaratorPropertiesExtractor.ts:42:21)
    at t.extract (C:\Projects\myApp\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\node-transformers\converting-transformers\ObjectExpressionKeysTransformer.ts:104:36)
    at transformNode (C:\Projects\myApp\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\node-transformers\converting-transformers\ObjectExpressionKeysTransformer.ts:67:33)
    at Controller.visitorFunction (C:\Projects\myApp\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\node-transformers\TransformersRunner.ts:111:55)
    at Controller.__execute (C:\Projects\myApp\node_modules\estraverse\estraverse.js:397:31)
    at Controller.replace (C:\Projects\myApp\node_modules\estraverse\estraverse.js:637:27)
error Command failed with exit code 1.
```

## Minimal working example that will help to reproduce issue
Unknown

**Comment by Slapbox** [comment]
No idea how to produce this error without providing my entire source code, which I can't. This is also an issue in 0.16.0 after upgrading to Node 10.9.0, if that gives any clues. 0.16.0 worked fine with Node 8.9.3.

Any thoughts on that thread of a clue?

**Comment by Slapbox** [comment]
I think I lied about `0.16.0` I will update again if I can confirm the issue in `0.16.0`.

**Comment by sanex3339** [comment]
Hi, i'll look into this issue but currently i take a 1-2 months timeout with this project to doing renovations on my flat. So, until october i'll have no time to look into this.

**Comment by Slapbox** [comment]
@sanex3339 thanks for the update. Just wanted to update this to confirm `0.16.0` works fine. Hope your renovations go well!

**Comment by sanex3339** [comment]
Easy, bot

**Comment by tomfree** [comment]
Am encountering it on 0.18

**Comment by zamotkin** [comment]
@Slapbox ,@tomfree: please try version 0.18.4, this bug should be fixed. Please write me if I'm wrong.

**Comment by Instupelligident** [comment]
Hello.  I tried testing this using my application and when trying to use the transformObjectKeys option, I received the same "Cannot read property 'type' of undefined" error.  Currently, I am using version 2.10.3 but did go through this thread and tried the .16 and .18 before writing this up (I am receiving the error on them all).  I was wondering if anyone had the ability to relook into this.
