### ISSUE TITLE
Doesn't show which file has syntax error

### ISSUE THREAD

**Issue by prakashgp** [javascript-obfuscator/javascript-obfuscator#334]
## Expected Behavior
Should show the file with full path which can't be obfuscated due to errors like Syntax Error, Unexpected Token error, etc

## Current Behavior
Currently it shows stack trace of the library itself. Which makes me stuck trying to find culprit js file  for hours. 

## Steps to Reproduce (for bugs)

1. Create a js file with invalid syntax
2. Run javascript obfuscator with this file as input
3. Output shows error, but doesn't tell us which file has the error. only line number and error type

## Your Environment

* Obfuscator version used: 0.9.4
* Node version used: v8.11.4

# Stack trace

```
/mnt/2301305734B29845/Development/linkedin_tools/node_modules/javascript-obfuscator/node_modules/esprima/dist/esprima.js:3396
	        var error = new Error(msg);
                     ^
Error: Line 539: Unexpected end of input
    at ErrorHandler.constructError (/mnt/2301305734B29845/Development/linkedin_tools/node_modules/javascript-obfuscator/node_modules/esprima/dist/esprima.js:3396:22)
    at ErrorHandler.createError (/mnt/2301305734B29845/Development/linkedin_tools/node_modules/javascript-obfuscator/node_modules/esprima/dist/esprima.js:3414:27)
    at Parser.unexpectedTokenError (/mnt/2301305734B29845/Development/linkedin_tools/node_modules/javascript-obfuscator/node_modules/esprima/dist/esprima.js:542:39)
    at Parser.throwUnexpectedToken (/mnt/2301305734B29845/Development/linkedin_tools/node_modules/javascript-obfuscator/node_modules/esprima/dist/esprima.js:552:21)
    at Parser.parsePrimaryExpression (/mnt/2301305734B29845/Development/linkedin_tools/node_modules/javascript-obfuscator/node_modules/esprima/dist/esprima.js:946:23)
    at Parser.inheritCoverGrammar (/mnt/2301305734B29845/Development/linkedin_tools/node_modules/javascript-obfuscator/node_modules/esprima/dist/esprima.js:833:37)
    at Parser.parseLeftHandSideExpressionAllowCall (/mnt/2301305734B29845/Development/linkedin_tools/node_modules/javascript-obfuscator/node_modules/esprima/dist/esprima.js:1388:26)
    at Parser.inheritCoverGrammar (/mnt/2301305734B29845/Development/linkedin_tools/node_modules/javascript-obfuscator/node_modules/esprima/dist/esprima.js:833:37)
    at Parser.parseUpdateExpression (/mnt/2301305734B29845/Development/linkedin_tools/node_modules/javascript-obfuscator/node_modules/esprima/dist/esprima.js:1482:26)
    at Parser.parseUnaryExpression (/mnt/2301305734B29845/Development/linkedin_tools/node_modules/javascript-obfuscator/node_modules/esprima/dist/esprima.js:1517:26)

```
## Minimal working example that will help to reproduce issue

```
// syntaxError.js
var person = {
name: 'Foo'
age: 10
}
```

**Comment by zamotkin** [comment]
Please notice, that now Obfuscator produces human-readable error report:

> Error: Line 3: Unexpected token age
> > ...age: 10...

**Comment by zamotkin** [comment]
@prakashgp if you still have questions feel free to re-open an issue.
