### ISSUE TITLE
ReferenceError: internalBinding is not defined

### ISSUE THREAD

**Issue by kodeine** [javascript-obfuscator/javascript-obfuscator#367]
Crashes if using with Ionic framework.

Config
```
prodConfig.plugins.push(
        new JavaScriptObfuscator({
            compact: true,
            controlFlowFlattening: false,
            deadCodeInjection: false,
            debugProtection: true,
            debugProtectionInterval: true,
            disableConsoleOutput: true,
            identifierNamesGenerator: 'hexadecimal',
            log: false,
            renameGlobals: false,
            rotateStringArray: true,
            selfDefending: true,
            stringArray: true,
            stringArrayEncoding: 'base64',
            stringArrayThreshold: 0.75,
            unicodeEscapeSequence: false
        }, ['main.js', 'polyfills.js', 'vendor.js', 'workbox-sw.js', 'graceful-fs/*', 'natives/*', 'node_modules/*'])
    );
```

```
fs.js:25
'use strict';
^

ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ (/projects/aa/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/projects/aa/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/projects/aa/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
```

**Comment by zamotkin** [comment]
@kodeine if you still have an issue, please provide a minimal working example to solve a problem.

**Comment by sanex3339** [comment]
Closed. Please, reopen the issue if you still have the problem
