### ISSUE TITLE
Error: Cannot find module 'babel-runtime/helpers/classCallCheck'

### ISSUE THREAD

**Issue by Boscop** [javascript-obfuscator/javascript-obfuscator#37]
I did `npm install -g javascript-obfuscator` but whenever I try to run it, I get:
> Error: Cannot find module 'babel-runtime/helpers/classCallCheck'

E.g.:
```
> javascript-obfuscator --help
Error: Cannot find module 'babel-runtime/helpers/classCallCheck'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\me\AppData\Roaming\npm\node_modules\javascri
pt-obfuscator\dist\webpack:\external "babel-runtime\helpers\classCallCheck":1:1)

    at __webpack_require__ (C:\Users\me\AppData\Roaming\npm\node_modules\javascr
ipt-obfuscator\dist\webpack:\webpack\bootstrap e2fb854ce0768d6a61f0:19:1)
    at Object.<anonymous> (C:\Users\me\AppData\Roaming\npm\node_modules\javascri
pt-obfuscator\dist\index.js:2783:24)
    at __webpack_require__ (C:\Users\me\AppData\Roaming\npm\node_modules\javascr
ipt-obfuscator\dist\webpack:\webpack\bootstrap e2fb854ce0768d6a61f0:19:1)
    at Object.module.exports.i (C:\Users\me\AppData\Roaming\npm\node_modules\jav
ascript-obfuscator\dist\webpack:\src\JavaScriptObfuscator.ts:12:1)
    at __webpack_require__ (C:\Users\me\AppData\Roaming\npm\node_modules\javascr
ipt-obfuscator\dist\webpack:\webpack\bootstrap e2fb854ce0768d6a61f0:19:1)
```

**Comment by MagicInventor** [comment]
me too 
https://puu.sh/tGioh.png

**Comment by sanex3339** [comment]
Found error. For some reason some reason `awesome-typescript-loader` cached some files and `babel-runtime` requires was adding to bundle file.

Will fix it in few hours, when i will go to work.

**Comment by sanex3339** [comment]
please try `javascript-obfuscator@0.9.1`

**Comment by Boscop** [comment]
Works, thanks!

**Comment by sanex3339** [comment]
Nice!
