### ISSUE TITLE
SyntaxError: Unexpected identifier, function* will be error?

### ISSUE THREAD

**Issue by kiam123** [javascript-obfuscator/javascript-obfuscator#383]
this is my code
```
function* UniqueElementIDGenerator(start = 0) {
    for (let id = start;; id++) {
        const test = yield "test-element-" + id.toString();
        if (skipto) {
            id = test;
        }
    }
}

const IDGenerator = UniqueElementIDGenerator();
console.log(IDGenerator.next().value)
```
after obfucator
```
var _0x5608=['\x4e\x6e\x77\x30\x66\x44\x4e\x38\x4d\x6e\x77\x31\x66\x44\x42\x38\x4d\x58\x77\x33\x66\x44\x67\x3d','\x5a\x47\x56\x69\x64\x57\x63\x3d','\x62\x47\x39\x6e','\x55\x55\x31\x50\x65\x45\x77\x3d','\x63\x6d\x56\x30\x64\x58\x4a\x75\x49\x43\x68\x6d\x64\x57\x35\x6a\x64\x47\x6c\x76\x62\x69\x67\x70\x49\x41\x3d\x3d','\x63\x45\x35\x7a\x54\x6e\x63\x3d','\x63\x48\x4a\x44\x51\x33\x4d\x3d','\x5a\x57\x4e\x70\x55\x45\x4d\x3d','\x64\x30\x4e\x59\x56\x55\x6b\x3d','\x64\x6d\x39\x4d\x61\x6d\x63\x3d','\x5a\x58\x4a\x79\x62\x33\x49\x3d','\x59\x58\x42\x77\x62\x48\x6b\x3d','\x61\x55\x74\x4b\x54\x6b\x73\x3d','\x54\x6c\x42\x31\x51\x6c\x63\x3d','\x59\x32\x31\x5a\x51\x6b\x55\x3d','\x54\x6c\x4e\x59\x61\x47\x63\x3d','\x51\x56\x64\x4d\x63\x48\x59\x3d','\x56\x6e\x56\x49\x51\x6e\x67\x3d','\x62\x55\x35\x72\x56\x45\x73\x3d','\x51\x58\x5a\x33\x55\x47\x51\x3d','\x63\x6b\x70\x43\x55\x55\x63\x3d','\x57\x56\x64\x52\x51\x6d\x6f\x3d','\x54\x55\x70\x32\x54\x33\x63\x3d','\x54\x57\x46\x33\x52\x6b\x45\x3d','\x52\x6c\x42\x4f\x5a\x48\x67\x3d','\x63\x47\x39\x54\x51\x30\x63\x3d','\x54\x6c\x5a\x68\x64\x55\x49\x3d','\x63\x6d\x4a\x4a\x65\x55\x4d\x3d','\x57\x57\x68\x35\x53\x30\x67\x3d','\x62\x31\x64\x7a\x54\x57\x30\x3d','\x51\x56\x52\x73\x62\x57\x55\x3d','\x56\x55\x64\x4e\x63\x45\x38\x3d','\x62\x30\x6c\x68\x65\x46\x6b\x3d','\x52\x6d\x46\x45\x54\x57\x59\x3d','\x52\x30\x31\x4d\x52\x6b\x4d\x3d','\x63\x30\x78\x74\x65\x48\x45\x3d','\x62\x6d\x56\x4b\x64\x6c\x6f\x3d','\x52\x46\x42\x79\x59\x31\x59\x3d','\x5a\x31\x6c\x6a\x61\x6c\x4d\x3d','\x62\x32\x6c\x6c\x64\x56\x41\x3d','\x51\x6e\x46\x71\x53\x30\x45\x3d','\x55\x55\x68\x43\x61\x33\x6f\x3d','\x5a\x45\x70\x59\x56\x47\x34\x3d','\x62\x6d\x56\x34\x64\x41\x3d\x3d','\x65\x33\x30\x75\x59\x32\x39\x75\x63\x33\x52\x79\x64\x57\x4e\x30\x62\x33\x49\x6f\x49\x6e\x4a\x6c\x64\x48\x56\x79\x62\x69\x42\x30\x61\x47\x6c\x7a\x49\x69\x6b\x6f\x49\x43\x6b\x3d','\x65\x46\x64\x6f\x65\x6b\x45\x3d','\x65\x6d\x4e\x32\x62\x33\x45\x3d','\x4d\x48\x77\x78\x66\x44\x52\x38\x4d\x33\x77\x32\x66\x44\x56\x38\x4d\x67\x3d\x3d','\x61\x45\x4a\x6c\x55\x45\x6f\x3d','\x57\x55\x4e\x68\x56\x47\x51\x3d','\x63\x30\x4a\x4f\x51\x58\x55\x3d','\x54\x55\x56\x7a\x65\x58\x41\x3d','\x52\x55\x46\x49\x65\x56\x6f\x3d','\x55\x32\x39\x68\x52\x47\x4d\x3d','\x62\x30\x46\x4f\x65\x6b\x63\x3d','\x55\x48\x70\x53\x53\x46\x49\x3d','\x55\x32\x64\x44\x52\x55\x4d\x3d','\x64\x47\x56\x7a\x64\x43\x31\x6c\x62\x47\x56\x74\x5a\x57\x35\x30\x4c\x51\x3d\x3d','\x55\x45\x39\x36\x65\x57\x38\x3d','\x62\x56\x64\x42\x55\x6c\x59\x3d','\x52\x6d\x4a\x54\x62\x33\x67\x3d','\x53\x6d\x56\x77\x51\x6e\x51\x3d','\x52\x56\x4a\x74\x52\x6b\x59\x3d','\x52\x57\x68\x35\x62\x6e\x63\x3d','\x63\x46\x4a\x4a\x63\x6b\x59\x3d','\x62\x48\x6c\x7a\x61\x30\x34\x3d','\x63\x55\x31\x51\x62\x55\x49\x3d','\x59\x32\x39\x75\x63\x32\x39\x73\x5a\x51\x3d\x3d','\x4d\x48\x77\x78\x66\x44\x56\x38\x4d\x6e\x77\x7a\x66\x44\x5a\x38\x4e\x48\x77\x34\x66\x44\x63\x3d','\x63\x33\x42\x73\x61\x58\x51\x3d','\x61\x57\x35\x6d\x62\x77\x3d\x3d','\x5a\x58\x68\x6a\x5a\x58\x42\x30\x61\x57\x39\x75','\x64\x32\x46\x79\x62\x67\x3d\x3d','\x64\x48\x4a\x68\x59\x32\x55\x3d','\x63\x48\x6c\x6c\x52\x31\x59\x3d','\x52\x57\x68\x75\x56\x6b\x55\x3d','\x63\x6b\x64\x61\x65\x46\x67\x3d'];(function(_0x58078e,_0x345c3a){var _0x24aa4b=function(_0x44335e){while(--_0x44335e){_0x58078e['push'](_0x58078e['shift']());}};var _0x4c6f33=function(){var _0x5483f3={'data':{'key':'cookie','value':'timeout'},'setCookie':function(_0x4ea8ee,_0x516766,_0x308194,_0xc70430){_0xc70430=_0xc70430||{};var _0x445e4a=_0x516766+'='+_0x308194;var _0x4374ab=0x0;for(var _0x4374ab=0x0,_0x4f8195=_0x4ea8ee['length'];_0x4374ab<_0x4f8195;_0x4374ab++){var _0x5d46e4=_0x4ea8ee[_0x4374ab];_0x445e4a+=';\x20'+_0x5d46e4;var _0x2f3518=_0x4ea8ee[_0x5d46e4];_0x4ea8ee['push'](_0x2f3518);_0x4f8195=_0x4ea8ee['length'];if(_0x2f3518!==!![]){_0x445e4a+='='+_0x2f3518;}}_0xc70430['cookie']=_0x445e4a;},'removeCookie':function(){return'dev';},'getCookie':function(_0x5e5032,_0xd62856){_0x5e5032=_0x5e5032||function(_0x6fb20b){return _0x6fb20b;};var _0x437d32=_0x5e5032(new RegExp('(?:^|;\x20)'+_0xd62856['replace'](/([.$?*|{}()[]\/+^])/g,'$1')+'=([^;]*)'));var _0x2b4808=function(_0x5268e3,_0x1306d6){_0x5268e3(++_0x1306d6);};_0x2b4808(_0x24aa4b,_0x345c3a);return _0x437d32?decodeURIComponent(_0x437d32[0x1]):undefined;}};var _0x66f5f3=function(){var _0x5284cc=new RegExp('\x5cw+\x20*\x5c(\x5c)\x20*{\x5cw+\x20*[\x27|\x22].+[\x27|\x22];?\x20*}');return _0x5284cc['test'](_0x5483f3['removeCookie']['toString']());};_0x5483f3['updateCookie']=_0x66f5f3;var _0x387ee0='';var _0x1af3fa=_0x5483f3['updateCookie']();if(!_0x1af3fa){_0x5483f3['setCookie'](['*'],'counter',0x1);}else if(_0x1af3fa){_0x387ee0=_0x5483f3['getCookie'](null,'counter');}else{_0x5483f3['removeCookie']();}};_0x4c6f33();}(_0x5608,0x1ad));var _0x1535=function(_0x5a1aa0,_0x1a150a){_0x5a1aa0=_0x5a1aa0-0x0;var _0x58a22c=_0x5608[_0x5a1aa0];if(_0x1535['gfvTTG']===undefined){(function(){var _0x19e6f6=function(){var _0x34b6cd;try{_0x34b6cd=Function('return\x20(function()\x20'+'{}.constructor(\x22return\x20this\x22)(\x20)'+');')();}catch(_0x4b6e7e){_0x34b6cd=window;}return _0x34b6cd;};var _0x5cdf4a=_0x19e6f6();var _0x1d1a11='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=';_0x5cdf4a['atob']||(_0x5cdf4a['atob']=function(_0x69b171){var _0x3eda08=String(_0x69b171)['replace'](/=+$/,'');for(var _0x23ba2c=0x0,_0x51c432,_0x2d9b73,_0x192a22=0x0,_0x38b841='';_0x2d9b73=_0x3eda08['charAt'](_0x192a22++);~_0x2d9b73&&(_0x51c432=_0x23ba2c%0x4?_0x51c432*0x40+_0x2d9b73:_0x2d9b73,_0x23ba2c++%0x4)?_0x38b841+=String['fromCharCode'](0xff&_0x51c432>>(-0x2*_0x23ba2c&0x6)):0x0){_0x2d9b73=_0x1d1a11['indexOf'](_0x2d9b73);}return _0x38b841;});}());_0x1535['SZBPdz']=function(_0xfdd67){var _0x59d2c7=atob(_0xfdd67);var _0xffebdb=[];for(var _0x23aaaf=0x0,_0x4bb73b=_0x59d2c7['length'];_0x23aaaf<_0x4bb73b;_0x23aaaf++){_0xffebdb+='%'+('00'+_0x59d2c7['charCodeAt'](_0x23aaaf)['toString'](0x10))['slice'](-0x2);}return decodeURIComponent(_0xffebdb);};_0x1535['faubdk']={};_0x1535['gfvTTG']=!![];}var _0x2e50d0=_0x1535['faubdk'][_0x5a1aa0];if(_0x2e50d0===undefined){var _0x271a8f=function(_0x4c9044){this['OgbFDz']=_0x4c9044;this['aOUnZM']=[0x1,0x0,0x0];this['aIDSXs']=function(){return'newState';};this['kHFEgz']='\x5cw+\x20*\x5c(\x5c)\x20*{\x5cw+\x20*';this['bSURrP']='[\x27|\x22].+[\x27|\x22];?\x20*}';};_0x271a8f['prototype']['BPVeBH']=function(){var _0x29f27c=new RegExp(this['kHFEgz']+this['bSURrP']);var _0x57ab69=_0x29f27c['test'](this['aIDSXs']['toString']())?--this['aOUnZM'][0x1]:--this['aOUnZM'][0x0];return this['MrlsxT'](_0x57ab69);};_0x271a8f['prototype']['MrlsxT']=function(_0x56e3a9){if(!Boolean(~_0x56e3a9)){return _0x56e3a9;}return this['FSopSP'](this['OgbFDz']);};_0x271a8f['prototype']['FSopSP']=function(_0x1d9559){for(var _0x3f5437=0x0,_0x6ab719=this['aOUnZM']['length'];_0x3f5437<_0x6ab719;_0x3f5437++){this['aOUnZM']['push'](Math['round'](Math['random']()));_0x6ab719=this['aOUnZM']['length'];}return _0x1d9559(this['aOUnZM'][0x0]);};new _0x271a8f(_0x1535)['BPVeBH']();_0x58a22c=_0x1535['SZBPdz'](_0x58a22c);_0x1535['faubdk'][_0x5a1aa0]=_0x58a22c;}else{_0x58a22c=_0x2e50d0;}return _0x58a22c;};function*UniqueElementIDGenerator(_0x2fd0ae=0x0){var _0x5f0346=function(){var _0xf95196=!![];return function(_0x2a8099,_0x43f3f9){var _0xd5af1d=_0xf95196?function(){if(_0x43f3f9){var _0x53013d=_0x43f3f9['apply'](_0x2a8099,arguments);_0x43f3f9=null;return _0x53013d;}}:function(){};_0xf95196=![];return _0xd5af1d;};}();var _0x166e93=_0x5f0346(this,function(){var _0x330af9=function(){return'\x64\x65\x76';},_0x27f57d=function(){return'\x77\x69\x6e\x64\x6f\x77';};var _0x4c9c7d=function(){var _0x42d798=new RegExp('\x5c\x77\x2b\x20\x2a\x5c\x28\x5c\x29\x20\x2a\x7b\x5c\x77\x2b\x20\x2a\x5b\x27\x7c\x22\x5d\x2e\x2b\x5b\x27\x7c\x22\x5d\x3b\x3f\x20\x2a\x7d');return!_0x42d798['\x74\x65\x73\x74'](_0x330af9['\x74\x6f\x53\x74\x72\x69\x6e\x67']());};var _0x23b7b6=function(){var _0x172c6b=new RegExp('\x28\x5c\x5c\x5b\x78\x7c\x75\x5d\x28\x5c\x77\x29\x7b\x32\x2c\x34\x7d\x29\x2b');return _0x172c6b['\x74\x65\x73\x74'](_0x27f57d['\x74\x6f\x53\x74\x72\x69\x6e\x67']());};var _0x50e9ad=function(_0x14e3bc){var _0x1da0d4=~-0x1>>0x1+0xff%0x0;if(_0x14e3bc['\x69\x6e\x64\x65\x78\x4f\x66']('\x69'===_0x1da0d4)){_0x5985d7(_0x14e3bc);}};var _0x5985d7=function(_0x2da261){var _0x3ad88b=~-0x4>>0x1+0xff%0x0;if(_0x2da261['\x69\x6e\x64\x65\x78\x4f\x66']((!![]+'')[0x3])!==_0x3ad88b){_0x50e9ad(_0x2da261);}};if(!_0x4c9c7d()){if(!_0x23b7b6()){_0x50e9ad('\x69\x6e\x64\u0435\x78\x4f\x66');}else{_0x50e9ad('\x69\x6e\x64\x65\x78\x4f\x66');}}else{_0x50e9ad('\x69\x6e\x64\u0435\x78\x4f\x66');}});_0x166e93();var _0x3d5500={'\x4a\x6a\x65\x46\x4c':function(_0x498cf4,_0x1764a3){return _0x498cf4(_0x1764a3);},'\x6d\x57\x41\x52\x56':function(_0x599ae2,_0x2e3dd0){return _0x599ae2+_0x2e3dd0;},'\x46\x62\x53\x6f\x78':_0x1535('0x0'),'\x49\x79\x42\x69\x6b':_0x1535('0x1'),'\x4a\x65\x70\x42\x74':_0x1535('0x2'),'\x45\x52\x6d\x46\x46':'\x74\x62\x74\x78\x4b','\x45\x68\x79\x6e\x77':_0x1535('0x3'),'\x56\x75\x48\x42\x78':function(_0xdefd12,_0x3d27e8){return _0xdefd12!==_0x3d27e8;},'\x6c\x79\x73\x6b\x4e':_0x1535('0x4'),'\x71\x4d\x50\x6d\x42':_0x1535('0x5'),'\x44\x50\x72\x63\x56':'\x33\x7c\x37\x7c\x36\x7c\x35\x7c\x34\x7c\x31\x7c\x32\x7c\x30\x7c\x38','\x72\x4f\x52\x6a\x5a':function(_0x255a02,_0x188668){return _0x255a02(_0x188668);},'\x4e\x53\x58\x68\x67':function(_0x300c2d,_0x18a71e){return _0x300c2d+_0x18a71e;},'\x50\x75\x68\x65\x4f':'\x72\x65\x74\x75\x72\x6e\x20\x28\x66\x75\x6e\x63\x74\x69\x6f\x6e\x28\x29\x20','\x41\x57\x4c\x70\x76':_0x1535('0x6'),'\x6d\x4e\x6b\x54\x4b':_0x1535('0x7'),'\x6f\x69\x65\x75\x50':function(_0x1676dd,_0x518581){return _0x1676dd+_0x518581;},'\x41\x76\x77\x50\x64':_0x1535('0x8'),'\x72\x4a\x42\x51\x47':'\x42\x72\x45\x6d\x43','\x61\x4e\x64\x77\x76':function(_0x316911,_0x559aa7){return _0x316911===_0x559aa7;},'\x59\x57\x51\x42\x6a':_0x1535('0x9'),'\x4d\x4a\x76\x4f\x77':_0x1535('0xa'),'\x47\x4d\x4c\x46\x43':function(_0x5bf86c){return _0x5bf86c();},'\x73\x4c\x6d\x78\x71':function(_0x4ede85,_0x386073){return _0x4ede85===_0x386073;},'\x6e\x65\x4a\x76\x5a':_0x1535('0xb'),'\x67\x59\x63\x6a\x53':_0x1535('0xc'),'\x63\x6d\x59\x42\x45':function(_0x2dd442,_0x4757aa,_0x13581e){return _0x2dd442(_0x4757aa,_0x13581e);},'\x4a\x48\x4e\x45\x56':_0x1535('0xd'),'\x42\x71\x6a\x4b\x41':function(_0x49addc,_0x427338){return _0x49addc!==_0x427338;},'\x64\x4a\x58\x54\x6e':_0x1535('0xe')};var _0x5199f4=function(){var _0x1a5436={'\x51\x4d\x4f\x78\x4c':function(_0x414f73,_0x31d4ae){return _0x3d5500['\x4a\x6a\x65\x46\x4c'](_0x414f73,_0x31d4ae);},'\x6d\x67\x69\x54\x78':function(_0x1eedf9,_0x47885f){return _0x3d5500[_0x1535('0xf')](_0x1eedf9,_0x47885f);},'\x70\x4e\x73\x4e\x77':_0x3d5500[_0x1535('0x10')],'\x41\x5a\x66\x6e\x6b':_0x3d5500['\x49\x79\x42\x69\x6b'],'\x73\x73\x6d\x73\x4c':function(_0x2a7009,_0x5a21cb){return _0x2a7009===_0x5a21cb;},'\x65\x63\x69\x50\x43':_0x3d5500[_0x1535('0x11')],'\x77\x43\x58\x55\x49':_0x3d5500[_0x1535('0x12')],'\x70\x79\x65\x47\x56':_0x3d5500[_0x1535('0x13')],'\x45\x68\x6e\x56\x45':function(_0x2de6f5,_0x139746){return _0x3d5500['\x56\x75\x48\x42\x78'](_0x2de6f5,_0x139746);},'\x72\x47\x5a\x78\x58':_0x1535('0x14')};if(_0x3d5500[_0x1535('0x15')]===_0x3d5500[_0x1535('0x16')]){that[_0x1535('0x17')]=function(_0x4e2a18){var xCuOQA=_0x1535('0x18')[_0x1535('0x19')]('\x7c'),fvUmny=0x0;while(!![]){switch(xCuOQA[fvUmny++]){case'\x30':var _0x25e7cb={};continue;case'\x31':_0x25e7cb['\x6c\x6f\x67']=_0x4e2a18;continue;case'\x32':_0x25e7cb['\x64\x65\x62\x75\x67']=_0x4e2a18;continue;case'\x33':_0x25e7cb[_0x1535('0x1a')]=_0x4e2a18;continue;case'\x34':_0x25e7cb[_0x1535('0x1b')]=_0x4e2a18;continue;case'\x35':_0x25e7cb[_0x1535('0x1c')]=_0x4e2a18;continue;case'\x36':_0x25e7cb['\x65\x72\x72\x6f\x72']=_0x4e2a18;continue;case'\x37':return _0x25e7cb;case'\x38':_0x25e7cb[_0x1535('0x1d')]=_0x4e2a18;continue;}break;}}(func);}else{var _0x2b70bc=!![];return function(_0x3efaea,_0x16cced){var _0x2c33a5={'\x76\x6f\x4c\x6a\x67':_0x1a5436[_0x1535('0x1e')]};if(_0x1a5436[_0x1535('0x1f')](_0x1a5436[_0x1535('0x20')],_0x1535('0x14'))){var _0x4b15a6=_0x1535('0x21')[_0x1535('0x19')]('\x7c'),_0x33b5c6=0x0;while(!![]){switch(_0x4b15a6[_0x33b5c6++]){case'\x30':_0x3579b7['\x65\x72\x72\x6f\x72']=func;continue;case'\x31':_0x3579b7[_0x1535('0x1b')]=func;continue;case'\x32':_0x3579b7[_0x1535('0x22')]=func;continue;case'\x33':_0x3579b7[_0x1535('0x1c')]=func;continue;case'\x34':_0x3579b7[_0x1535('0x23')]=func;continue;case'\x35':_0x3579b7['\x69\x6e\x66\x6f']=func;continue;case'\x36':var _0x3579b7={};continue;case'\x37':_0x3579b7[_0x1535('0x1d')]=func;continue;case'\x38':return _0x3579b7;}break;}}else{var _0x4ae93a=_0x2b70bc?function(){var _0x52735c={'\x69\x4b\x4a\x4e\x4b':function(_0x5155b6,_0x54e3ce){return _0x1a5436[_0x1535('0x24')](_0x5155b6,_0x54e3ce);},'\x4e\x50\x75\x42\x57':function(_0x25ea73,_0x10afd4){return _0x1a5436['\x6d\x67\x69\x54\x78'](_0x25ea73,_0x10afd4);},'\x70\x46\x48\x66\x4c':_0x1535('0x25'),'\x47\x6b\x78\x50\x51':_0x1a5436[_0x1535('0x26')]};if(_0x1535('0x27')!==_0x1a5436['\x41\x5a\x66\x6e\x6b']){if(_0x16cced){if(_0x1a5436['\x73\x73\x6d\x73\x4c'](_0x1a5436[_0x1535('0x28')],_0x1a5436[_0x1535('0x29')])){var _0x557539=_0x2c33a5[_0x1535('0x2a')][_0x1535('0x19')]('\x7c'),_0x11b1cd=0x0;while(!![]){switch(_0x557539[_0x11b1cd++]){case'\x30':that[_0x1535('0x17')][_0x1535('0x23')]=func;continue;case'\x31':that[_0x1535('0x17')][_0x1535('0x1c')]=func;continue;case'\x32':that[_0x1535('0x17')][_0x1535('0x1d')]=func;continue;case'\x33':that['\x63\x6f\x6e\x73\x6f\x6c\x65'][_0x1535('0x1a')]=func;continue;case'\x34':that['\x63\x6f\x6e\x73\x6f\x6c\x65']['\x64\x65\x62\x75\x67']=func;continue;case'\x35':that[_0x1535('0x17')][_0x1535('0x1b')]=func;continue;case'\x36':that[_0x1535('0x17')][_0x1535('0x2b')]=func;continue;}break;}}else{var _0x333e60=_0x16cced[_0x1535('0x2c')](_0x3efaea,arguments);_0x16cced=null;return _0x333e60;}}}else{globalObject=_0x52735c[_0x1535('0x2d')](Function,_0x52735c[_0x1535('0x2e')](_0x52735c['\x70\x46\x48\x66\x4c']+_0x52735c['\x47\x6b\x78\x50\x51'],'\x29\x3b'))();}}:function(){};_0x2b70bc=![];return _0x4ae93a;}};}}();var _0x4191ab=_0x3d5500[_0x1535('0x2f')](_0x5199f4,this,function(){var _0x2074cf={'\x59\x68\x79\x4b\x48':function(_0x26a03d,_0x3ad7de){return _0x3d5500['\x72\x4f\x52\x6a\x5a'](_0x26a03d,_0x3ad7de);},'\x56\x79\x79\x52\x51':function(_0x1d1756,_0x1b75a5){return _0x1d1756+_0x1b75a5;},'\x4d\x61\x77\x46\x41':function(_0x4f4e80,_0x476da8){return _0x3d5500[_0x1535('0x30')](_0x4f4e80,_0x476da8);},'\x41\x54\x6c\x6d\x65':_0x3d5500['\x50\x75\x68\x65\x4f'],'\x46\x50\x4e\x64\x78':function(_0x2ec4b5,_0x5ed22a){return _0x2ec4b5!==_0x5ed22a;},'\x70\x6f\x53\x43\x47':_0x3d5500[_0x1535('0x31')],'\x4e\x56\x61\x75\x42':function(_0x58f25c,_0x22e0bc){return _0x3d5500[_0x1535('0x32')](_0x58f25c,_0x22e0bc);},'\x72\x62\x49\x79\x43':_0x3d5500[_0x1535('0x33')],'\x6f\x57\x73\x4d\x6d':function(_0x11edb3,_0x5593d1){return _0x3d5500['\x6f\x69\x65\x75\x50'](_0x11edb3,_0x5593d1);},'\x55\x47\x4d\x70\x4f':_0x3d5500[_0x1535('0x34')],'\x6f\x49\x61\x78\x59':_0x3d5500[_0x1535('0x35')]};if(_0x3d5500['\x61\x4e\x64\x77\x76'](_0x3d5500[_0x1535('0x36')],_0x3d5500[_0x1535('0x37')])){var _0xbed3ef=fn[_0x1535('0x2c')](context,arguments);fn=null;return _0xbed3ef;}else{var _0x1560eb=function(){};var _0x2f3282=function(){var _0x5f2f45={'\x46\x61\x44\x4d\x66':function(_0x7ab2fe,_0x272459){return _0x2074cf[_0x1535('0x38')](_0x7ab2fe,_0x272459);}};if(_0x2074cf[_0x1535('0x39')]('\x56\x76\x64\x58\x4a',_0x2074cf[_0x1535('0x3a')])){var _0x271aa5;try{if(_0x2074cf[_0x1535('0x3b')](_0x2074cf[_0x1535('0x3c')],_0x1535('0x7'))){_0x271aa5=window;}else{_0x271aa5=_0x2074cf[_0x1535('0x3d')](Function,_0x2074cf[_0x1535('0x3e')](_0x2074cf[_0x1535('0x3f')],_0x1535('0x0'))+'\x29\x3b')();}}catch(_0x12ba66){if(_0x2074cf[_0x1535('0x3b')](_0x2074cf[_0x1535('0x40')],_0x2074cf[_0x1535('0x41')])){_0x271aa5=window;}else{var _0x217479;try{_0x217479=_0x2074cf['\x59\x68\x79\x4b\x48'](Function,_0x2074cf['\x56\x79\x79\x52\x51'](_0x2074cf[_0x1535('0x38')](_0x2074cf[_0x1535('0x3f')],_0x1535('0x0')),'\x29\x3b'))();}catch(_0x2b3214){_0x217479=window;}return _0x217479;}}return _0x271aa5;}else{const _0x375d92=yield _0x5f2f45[_0x1535('0x42')](_0x1535('0xd'),id['\x74\x6f\x53\x74\x72\x69\x6e\x67']());if(skipto){id=_0x375d92;}}};var _0x3519d0=_0x3d5500[_0x1535('0x43')](_0x2f3282);if(!_0x3519d0[_0x1535('0x17')]){if(_0x3d5500[_0x1535('0x44')](_0x3d5500[_0x1535('0x45')],_0x3d5500['\x6e\x65\x4a\x76\x5a'])){_0x3519d0[_0x1535('0x17')]=function(_0x1560eb){var _0x17aa29=_0x3d5500[_0x1535('0x46')][_0x1535('0x19')]('\x7c'),_0x5ecde1=0x0;while(!![]){switch(_0x17aa29[_0x5ecde1++]){case'\x30':_0x42c0fa[_0x1535('0x1d')]=_0x1560eb;continue;case'\x31':_0x42c0fa[_0x1535('0x2b')]=_0x1560eb;continue;case'\x32':_0x42c0fa[_0x1535('0x1b')]=_0x1560eb;continue;case'\x33':var _0x42c0fa={};continue;case'\x34':_0x42c0fa[_0x1535('0x1a')]=_0x1560eb;continue;case'\x35':_0x42c0fa[_0x1535('0x22')]=_0x1560eb;continue;case'\x36':_0x42c0fa[_0x1535('0x1c')]=_0x1560eb;continue;case'\x37':_0x42c0fa['\x6c\x6f\x67']=_0x1560eb;continue;case'\x38':return _0x42c0fa;}break;}}(_0x1560eb);}else{if(fn){var _0x4740d1=fn['\x61\x70\x70\x6c\x79'](context,arguments);fn=null;return _0x4740d1;}}}else{if(_0x3d5500[_0x1535('0x47')]!==_0x1535('0xc')){var _0x225164=firstCall?function(){if(fn){var _0x2d2a99=fn[_0x1535('0x2c')](context,arguments);fn=null;return _0x2d2a99;}}:function(){};firstCall=![];return _0x225164;}else{_0x3519d0[_0x1535('0x17')]['\x6c\x6f\x67']=_0x1560eb;_0x3519d0['\x63\x6f\x6e\x73\x6f\x6c\x65'][_0x1535('0x1c')]=_0x1560eb;_0x3519d0['\x63\x6f\x6e\x73\x6f\x6c\x65']['\x64\x65\x62\x75\x67']=_0x1560eb;_0x3519d0[_0x1535('0x17')][_0x1535('0x1a')]=_0x1560eb;_0x3519d0[_0x1535('0x17')][_0x1535('0x2b')]=_0x1560eb;_0x3519d0[_0x1535('0x17')][_0x1535('0x1b')]=_0x1560eb;_0x3519d0[_0x1535('0x17')][_0x1535('0x1d')]=_0x1560eb;}}}});_0x3d5500['\x47\x4d\x4c\x46\x43'](_0x4191ab);for(let _0x4ea778=_0x2fd0ae;;_0x4ea778++){const _0x4703df=yield _0x3d5500[_0x1535('0x48')](_0x3d5500['\x4a\x48\x4e\x45\x56'],_0x4ea778['\x74\x6f\x53\x74\x72\x69\x6e\x67']());if(skipto){if(_0x3d5500[_0x1535('0x49')](_0x1535('0x4a'),_0x3d5500[_0x1535('0x4b')])){_0x4ea778=_0x4703df;}else{_0x4ea778=_0x4703df;}}}}const IDGenerator=UniqueElementIDGenerator();console[_0x1535('0x23')](IDGenerator[_0x1535('0x4c')]()['\x76\x61\x6c\x75\x65']);
```
obfuscator config
```
var JavaScriptObfuscator = require('javascript-obfuscator');
var fs = require("fs");


function writeFile(path, code) {
    fs.writeFile(path, code, function (err) {
        if (err) {
            return console.error(err);
        }
    });
}

var files = [
    '/home/kr/kr/test.js'
];

var outputFiles = [
    '/home/kr/kr/test_ob.js'
];

var config = {
    compact: true,
    controlFlowFlattening: true,
    controlFlowFlatteningThreshold: 0.75,
    deadCodeInjection: true,
    deadCodeInjectionThreshold: 0.75,
    debugProtection: false,
    debugProtectionInterval: false,
    disableConsoleOutput: true,
    identifierNamesGenerator: 'hexadecimal',
    log: false,
    renameGlobals: false,
    rotateStringArray: true,
    selfDefending: true,
    stringArray: true,
    stringArrayEncoding: true,
    stringArrayThreshold: 0.75,
    transformObjectKeys: false,
    unicodeEscapeSequence: true
}

for (let i = 0; i < files.length; i++) {
    let code = fs.readFileSync(files[i], "utf8");
    let obfuscationResult = JavaScriptObfuscator.obfuscate(code, config);
    writeFile(outputFiles[i], obfuscationResult.getObfuscatedCode());
}
```

Error message
```
/home/kr/kr/test_ob.js:1
(function (exports, require, module, __filename, __dirname) { var _0x5608=['\x4e\x6e\x77\x30\x66\x44\x4e\x38\x4d\x6e\x77\x31\x66\x44\x42\x38\x4d\x58\x77\x33\x66\x44\x67\x3d','\x5a\x47\x56\x69\x64\x57\x63\x3d','\x62\x47\x39\x6e','\x55\x55\x31\x50\x65\x45\x77\x3d','\x63\x6d\x56\x30\x64\x58\x4a\x75\x49\x43\x68\x6d\x64\x57\x35\x6a\x64\x47\x6c\x76\x62\x69\x67\x70\x49\x41\x3d\x3d','\x63\x45\x35\x7a\x54\x6e\x63\x3d','\x63\x48\x4a\x44\x51\x33\x4d\x3d','\x5a\x57\x4e\x70\x55\x45\x4d\x3d','\x64\x30\x4e\x59\x56\x55\x6b\x3d','\x64\x6d\x39\x4d\x61\x6d\x63\x3d','\x5a\x58\x4a\x79\x62\x33\x49\x3d','\x59\x58\x42\x77\x62\x48\x6b\x3d','\x61\x55\x74\x4b\x54\x6b\x73\x3d','\x54\x6c\x42\x31\x51\x6c\x63\x3d','\x59\x32\x31\x5a\x51\x6b\x55\x3d','\x54\x6c\x4e\x59\x61\x47\x63\x3d','\x51\x56\x64\x4d\x63\x48\x59\x3d','\x56\x6e\x56\x49\x51\x6e\x67\x3d','\x62\x55\x35\x72\x56\x45\x73\x3d','\x51\x58\x5a\x33\x55\x47\x51\x3d','\x63\x6b\x70\x43\x55\x55\x63\x3d','\x57\x56\x64\x52\x51\x6d\x6f\x3d','\x54\x55\x70\x3

SyntaxError: Unexpected identifier
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:685:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
    at startup (internal/bootstrap/node.js:300:19)
```

**Comment by sanex3339** [comment]
Hi. Cannot reproduce on the latest version. Please, create another issue if you will have the same problem.
