### ISSUE TITLE
Cannot apply @injectable decorator multiple times

### ISSUE THREAD

**Issue by voxsoftware** [javascript-obfuscator/javascript-obfuscator#388]
## Expected Behavior
simply works

## Current Behavior
Throws an exception

## Steps to Reproduce (for bugs)
1. Nothing special, only obfuscate some code

## Your Environment
* Obfuscator version used: 0.18.0
* Node version used: 10.15.3

# Stack trace
```
Cannot apply @injectable decorator multiple times.","stack":"Error: Cannot apply @injectable decorator multiple times.\n    at /home/james/.kawi/npm-inst/javascript-obfuscator@0.18.1/node_modules/inversify/lib/annotation/injectable.js:8:19\n
    at DecorateConstructor (/home/james/.kawi/npm-inst/javascript-obfuscator@0.18.1/node_modules/reflect-metadata/Reflect.ts:1202:35)\n
 at Object.decorate (/home/james/.kawi/npm-inst/javascript-obfuscator@0.18.1/node_modules/reflect-metadata/Reflect.ts:742:24)\n
    at _decorate (/home/james/.kawi/npm-inst/javascript-obfuscator@0.18.1/node_modules/inversify/lib/annotation/decorator_utils.js:42:13)\n
    at Object.decorate (/home/james/.kawi/npm-inst/javascript-obfuscator@0.18.1/node_modules/inversify/lib/annotation/decorator_utils.js:55:9)\n
    at Object.decorate (/home/james/.kawi/npm-inst/javascript-obfuscator@0.18.1/dist/webpack:/JavaScriptObfuscator/src/event-emitters/ObfuscationEventEmitter.ts:7:1)\n    at call (/home/james/.kawi/npm-inst/javascript-obfuscator@0.18.1/dist/webpack:/JavaScriptObfuscator/webpack/bootstrap:19:1)\n
    at Object.__webpack_require__ (/home/james/.kawi/npm-inst/javascript-obfuscator@0.18.1/dist/webpack:/JavaScriptObfuscator/src/container/InversifyContainerFacade.ts:29:1)\n    at call (/home/james/.kawi/npm-inst/javascript-obfuscator@0.18.1/dist/webpack:/JavaScriptObfuscator/webpack/bootstrap:19:1)\n
    at Object.__webpack_require__ (/home/james/.kawi/npm-inst/javascript-obfuscator@0.18.1/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscatorFacade.ts:11:1)\n    at call (/home/james/.kawi/npm-inst/javascript-obfuscator@0.18.1/dist/webpack:/JavaScriptObfuscator/webpack/bootstrap:19:1)\n
    at Object.__webpack_require__ (/home/james/.kawi/npm-inst/javascript-obfuscator@0.18.1/dist/webpack:/JavaScriptObfuscator/index.ts:3:1)\n    at call (/home/james/.kawi/npm-inst/javascript-obfuscator@0.18.1/dist/webpack:/JavaScriptObfuscator/webpack/bootstrap:19:1)\n
     at __webpack_require__ (/home/james/.kawi/npm-inst/javascript-obfuscator@0.18.1/dist/webpack:/JavaScriptObfuscator/webpack/bootstrap:83:1)\n   
    at Object.<anonymous> (/home/james/.kawi/npm-inst/javascript-obfuscator@0.18.1/dist/webpack:/JavaScriptObfuscator/webpack/bootstrap:83:1)\n
    at Module._compile (internal/modules/cjs/loader.js:701:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)\n    at Module.load (internal/modules/cjs/loader.js:600:32)\n
    at nc (/home/james/projects/@kawix/core/crossplatform/src/KModule.js:1697:13)
```

## Minimal working example that will help to reproduce issue
```javascript
var JsObfuscator, originaltext;

JsObfuscator = require("javascript-obfuscator");

originaltext = "var __eval1__ =  function(str){\n	return eval(str)\n}\nvar Zlib = require('zlib')\nvar crypto = require('crypto')\nvar machineId = global.__machineId\nvar ___Executable, ___CIPKEY, ___ExecutableF\n\n\n___CIPKEY= function(password){\n	var buf= []\n	buf[0]= Buffer.from(password)\n	if(buf[0].length >= 32){\n		buf= buf[0].slice(0, 32)\n	}else{\n		buf.push(Buffer.allocUnsafe(32- buf[0].length))\n		buf[1].fill(1)\n		buf= Buffer.concat(buf)\n	}\n	return buf \n}\n\n\n___Executable = function(){\n\n	var content= Buffer.from(___CONTENT(), \"base64\")\n	var cipherKey = ___CIPKEY(machineId)\n	var initVect = content.slice(0, 16)\n	content = content.slice(16)\n	var decipher= crypto.createDecipheriv('aes256', cipherKey, initVect);\n	var decrypted = Buffer.concat([decipher.update(content), decipher.final()]);\n	decrypted = Zlib.gunzipSync(decrypted);\n\n	___ExecutableF=  __eval1__(\"(function(){\\n\" + decrypted.toString() + \"\\n})\")\n	\n\n}\n\n\n\nif(!___ExecutableF){\n	___Executable()\n}\n___ExecutableF() ";

JsObfuscator.obfuscate(originaltext, {
  compact: true,
  controlFlowFlattening: true,
  controlFlowFlatteningThreshold: 1,
  deadCodeInjection: true,
  deadCodeInjectionThreshold: 1,
  identifierNamesGenerator: 'hexadecimal',
  renameGlobals: false,
  rotateStringArray: true,
  selfDefending: true,
  stringArray: true,
  stringArrayEncoding: 'rc4',
  stringArrayThreshold: 1,
  transformObjectKeys: true,
  unicodeEscapeSequence: false
});

```

**Comment by zamotkin** [comment]
@voxsoftware I successfully obfuscated in 0.18.6 using your settings. I remove some escape for `"` mark. So I hope your bug is fixed.

```
var __eval1__ =  function(str){
	return eval(str)
}
var Zlib = require('zlib')
var crypto = require('crypto')
var machineId = global.__machineId
var ___Executable, ___CIPKEY, ___ExecutableF


___CIPKEY= function(password){
	var buf= []
	buf[0]= Buffer.from(password)
	if(buf[0].length >= 32){
		buf= buf[0].slice(0, 32)
	}else{
		buf.push(Buffer.allocUnsafe(32- buf[0].length))
		buf[1].fill(1)
		buf= Buffer.concat(buf)
	}
	return buf 
}


___Executable = function(){

	var content= Buffer.from(___CONTENT(), "base64")
	var cipherKey = ___CIPKEY(machineId)
	var initVect = content.slice(0, 16)
	content = content.slice(16)
	var decipher= crypto.createDecipheriv('aes256', cipherKey, initVect);
	var decrypted = Buffer.concat([decipher.update(content), decipher.final()]);
	decrypted = Zlib.gunzipSync(decrypted);

	___ExecutableF=  __eval1__("(function(){\
" + decrypted.toString() + "\
})")
	

}



if(!___ExecutableF){
	___Executable()
}
___ExecutableF() 
```
