### ISSUE TITLE
Error: Cannot read property 'ecmaFeatures' of undefined

### ISSUE THREAD

**Issue by Domuska** [javascript-obfuscator/javascript-obfuscator#389]
Hi! I'm encountering the same issue that was reported in [here](https://github.com/javascript-obfuscator/javascript-obfuscator/issues/287) and [here](https://github.com/javascript-obfuscator/webpack-obfuscator/issues/45). Since those threads are locked, I figured I should create a new issue as this still seems to be a problem.

Stack trace:

```
Error: Cannot read property 'ecmaFeatures' of undefined
    at Function.value (c:\development\myproject\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\EspreeFacade.ts:82:19)
    at Function.processParsingError (c:\development\myproject\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\EspreeFacade.ts:44:46)
    at e.parse (c:\development\myproject\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\JavaScriptObfuscator.ts:154:29)
    at e.parseCode (c:\development\myproject\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\JavaScriptObfuscator.ts:135:46)
    at Function.obfuscate (c:\development\myproject\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\JavaScriptObfuscatorFacade.ts:31:70)
    at c:\development\myproject\node_modules\webpack-obfuscator\index.js:49:66
    at Array.forEach (<anonymous>)
    at c:\development\myproject\node_modules\webpack-obfuscator\index.js:27:23
    at AsyncSeriesHook.eval [as callAsync] (eval at create (c:\development\myproject\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (c:\development\myproject\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.additionalAssets.callAsync.err (c:\development\myproject\node_modules\webpack\lib\Compilation.js:1309:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (c:\development\myproject\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (c:\development\myproject\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)
    at hooks.optimizeTree.callAsync.err (c:\development\myproject\node_modules\webpack\lib\Compilation.js:1305:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (c:\development\myproject\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (c:\development\myproject\node_modules\webpack\node_modules\tapable\lib\Hook.js:154:20)                                                                                     
```

Obfuscator version used: 0.18.1
Node version used: 8.12.0

I'm getting the error in title when I'm attempting to run JavascriptObfuscator in following way
```
fs.readFile('dist/file.js', (err, data) => {
    const obfuscationResult = JavaScriptObfuscator.obfuscate(data.toString('utf-8'));
    fs.writeFile('dist/obfuscated.js', obfuscationResult.getObfuscatedCode(), (err) => {
        console.log('all done');
    });
});
```

I'd expect the obfuscated code to be written into dist/obfuscated.js, but instead I'm getting the error above.

I dug a bit into the problem (as it was also discussed [here](https://github.com/eslint/eslint/issues/10623). It seems according to the eslint repo discussion that there is an issue with Espree being loaded multiple times or something along those lines, and the issue being fixed at newer version of Espree. At least for me the problem was solved by manually updating javascript-obfuscator's Espree version from 4.0.0 to 5.0.1 in my node_modules, deleting javascript-obfuscator's node_modules and re-running `npm install`.  All seemed fine to me afterwards, is this something that could be included in the next release of the library?

I can try to re-create the error situation with a full downloadable repo when have the time for it, if you wish.

**Comment by zamotkin** [comment]
Upgraded Espree to 6.1.2 #443
