### ISSUE TITLE
Obfuscator crashes with error unterminated regex

### ISSUE THREAD

**Issue by fazerlicourice7** [javascript-obfuscator/javascript-obfuscator#393]
See title. 
Stack trace and code below. Fails on other code samples as well.

## Your Environment

* Obfuscator version used: 0.18.1
* Node version used: 6.16.0

# Stack trace
/usr/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/EspreeFacade.ts:100
        throw new Error(`Line ${position.line}: ${errorMessage}\n${formattedPointer} ${formattedCodeSlice}`);
              ^
Error: Line 18: Unterminated regular expression
> .../...
    at Function.value (/usr/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/EspreeFacade.ts:100:15)
    at Function.processParsingError (/usr/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/EspreeFacade.ts:44:46)
    at e.parse (/usr/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscator.ts:154:29)
    at e.parseCode (/usr/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscator.ts:135:46)
    at Function.obfuscate (/usr/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscatorFacade.ts:31:70)
    at Function.obfuscate (/usr/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/cli/JavaScriptObfuscatorCLI.ts:109:61)
    at e.processSourceCodeWithoutSourceMap (/usr/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/cli/JavaScriptObfuscatorCLI.ts:410:37)
    at e.apply (/usr/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/decorators/Initializable.ts:105:39)
    at e.processSourceCode (/usr/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/cli/JavaScriptObfuscatorCLI.ts:372:18)
    at e.apply (/usr/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/decorators/Initializable.ts:105:39)

## Minimal working example that will help to reproduce issue
```javascript
async function getSessionFromStorage() {
	return Promise.resolve(localStorage.getItem("nakamatoken"));
}
async function storeSession(session) {
	await localStorage.setItem("nakamatoken", session.token_);
}
async function leaderBoards() {
	var sessionString = await getSessionFromStorage();
	if (sessionString && sessionString != "") {

		var session = await nakamajs.Session.restore(sessionString);

		  if (!session.isexpired(new Date())) {
		  	
		    await Promise.resolve(session);
		  } 
	} else {
		/
	}

	var session = await nakamajs.Session.restore(sessionString);
	if(session.isexpired(new Date())){
		console.log(session.isexpired(new Date()))
		//alert("Your session has expired: logging out");
		await localStorage.removeItem("nakamatoken");

		

		
	}
	
	console.log(session);
	
	
	
}
async function authenticte() {
	//Authenticates with test user
	var customId = "____";
	var username = "_____";
	var client = new nakamajs.Client(nakamaConfig.serverKey, nakamaConfig.host, nakamaConfig.port, nakamaConfig.useSSL);
	client.ssl = nakamaConfig.useSSL;
	try{
			
			var message = nakamajs.AuthenticateRequest.custom(customId);
			
			client.login(message).then(function(session){
			  console.log("Successfully logged in, session: %o", new Date(session.expiresAt));
			  
			  storeSession(session);

			  client.connect(session).then(function() {
				message = new nakamajs.SelfUpdateRequest();
			    message.handle = username;
			    client.send(message).then(function() {
			    	var client = new nakamajs.Client(nakamaConfig.serverKey, nakamaConfig.host, nakamaConfig.port, nakamaConfig.useSSL);
					client.ssl = nakamaConfig.useSSL;
			    	message = nakamajs.AuthenticateRequest.custom(customId);
			    	client.login(message).then(function(session) {
			    		storeSession(session).then(function() {
			    			leaderBoards();
			    		});
			    		

			    	}).catch(function(error) {
			    		if(error === 'jwt is not valid.') {
							localStorage.setItem("nakamatoken", '')
						} else {

						} if(error.message) {
							console.log(error.message);
						} else {
							console.log("failed to login");

						}
			    	})
			    }).catch(function(error){
			  	  console.log(error);

				  console.log(error.message);
				})
			  }).catch(function(error) {
			  	if(error.message) {
					console.log(error.message);
				} else {
					Console.log("failed to login");

				}
			  })
			  
			 
			  
			}).catch(function(error) {
				console.log(error.message);
			})
			
		} catch(e) {
			if(e === 'jwt is not valid.') {
				localStorage.setItem("nakamatoken", '')
			} else {

			} if(e.message) {
				$('#success').html(e.message);
			} else {
				$('#success').html("failed to login");

			}
		}
}
async function call() {
	await authenticte();
	
}



$(document).ready(function(evt) {
	
	
	$('#logout').click(function(evt) {
		if(confirm("Logout?")){
			localStorage.removeItem("nakamatoken");

			window.location.replace("./index.html");

		}
	});

	$(".num_players").click(function(evt) {
		
		var num_players = evt.target.id;
		var players;
		if(num_players === "2players") {
			players = "'2'";
			
		} else if (num_players === "3players") {
			players = "'3'";
		}

		var iframe = `<iframe class='embed-responsive-item' id='unityplayer' src='./game.html' game-mode='tutorial' num-players=${players} width='1280' height='720'></iframe>`;
		var div = `<div class='embed-responsive embed-responsive-4by3'>${iframe}</div>`;
		$("#play-now").html(div);
		
	})
	call();

	
	
});
```

**Comment by GaikwadPratik** [comment]
@sanex3339 , I am getting the same issue.

javascript-obfuscator version 0.18.1, nodejs version: 10.16.0
stack:
```
/home/pratik/hive/code/hive-fabric/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/EspreeFacade.ts:100
throw new Error(`Line ${position.line}: ${errorMessage}\n${formattedPointer} ${formattedCodeSlice}`);
      ^
Error: Line 132: Unexpected token {
> ...catch {...
    at Function.value (/home/pratik/hive/code/hive-fabric/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/EspreeFacade.ts:100:15)
    at Function.processParsingError (/home/pratik/hive/code/hive-fabric/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/EspreeFacade.ts:44:46)
    at e.parse (/home/pratik/hive/code/hive-fabric/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscator.ts:154:29)
    at e.parseCode (/home/pratik/hive/code/hive-fabric/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscator.ts:135:46)
    at Function.obfuscate (/home/pratik/hive/code/hive-fabric/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscatorFacade.ts:31:70)
    at Function.obfuscate (/home/pratik/hive/code/hive-fabric/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/cli/JavaScriptObfuscatorCLI.ts:134:70)
    at e.processSourceCodeWithSourceMap (/home/pratik/hive/code/hive-fabric/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/cli/JavaScriptObfuscatorCLI.ts:408:37)
    at e.apply (/home/pratik/hive/code/hive-fabric/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/decorators/Initializable.ts:105:39)
    at processSourceCode (/home/pratik/hive/code/hive-fabric/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/cli/JavaScriptObfuscatorCLI.ts:379:22)
    at Array.forEach (<anonymous>)```

usage:

```node_modules/.bin/javascript-obfuscator ./dist --output ./dist/obfuscated --compact true --disable-console-output true --source-map true --source-map-mode inline```

Please let me know if you need anymore information

**Comment by GaikwadPratik** [comment]
@sanex3339 ,
upon doing some research, the error for me is coming from `espree`. I am wondering if its possible to add `filePath` in the error message in `processSourceCodeData` function. I am ready to create a PR, just wondering if there any reason why it wasn't done earlier? Also can you upgrade packages and release a new package, as I suspect `espree` package might have fixed the issue that I have.

**Comment by zamotkin** [comment]
@fazerlicourice7 I see an error in your source javascript and obfuscator reports it correctly:
```
Error: Line 18: Unterminated regular expression
> .../...
```

The code below is not valid as you can see:
```
} else {
		/
	}
```

What did you expect from obfuscator in this case? Any thoughts how to report about errors in source code more clear?
