### ISSUE TITLE
>npx webpack --config webpack/webpack.browser.config.js

### ISSUE THREAD

**Issue by lonewolfyx** [javascript-obfuscator/javascript-obfuscator#404]
I use the above command to pop up the following error

Babel compiler cannot be found, please add it to your package.json file:
npm install --save-dev babel-core

{ Error: Cannot find module '@babel/core'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (F:\test-webpack\javascript-obfuscator\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at setupBabel (F:\test-webpack\javascript-obfuscator\node_modules\awesome-typescript-loader\src\instance.ts:252:16)
    at Object.ensureInstance (F:\test-webpack\javascript-obfuscator\node_modules\awesome-typescript-loader\src\instance.ts:130:18)
    at compiler (F:\test-webpack\javascript-obfuscator\node_modules\awesome-typescript-loader\src\index.ts:45:19)
    at Object.loader (F:\test-webpack\javascript-obfuscator\node_modules\awesome-typescript-loader\src\index.ts:14:12)
    at LOADER_EXECUTION (F:\test-webpack\javascript-obfuscator\node_modules\loader-runner\lib\LoaderRunner.js:119:14)
    at runSyncOrAsync (F:\test-webpack\javascript-obfuscator\node_modules\loader-runner\lib\LoaderRunner.js:120:4)
    at iterateNormalLoaders (F:\test-webpack\javascript-obfuscator\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (F:\test-webpack\javascript-obfuscator\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (F:\test-webpack\javascript-obfuscator\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:43:16)
    at provider (F:\test-webpack\javascript-obfuscator\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:79:9)
    at F:\test-webpack\javascript-obfuscator\node_modules\graceful-fs\graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3) code: 'MODULE_NOT_FOUND' }

need you help~

**Comment by zamotkin** [comment]
Did you install babel-core?

**Comment by sanex3339** [comment]
Closed because of lack of the information.
Please, recreate a new issue if you will have additional questions.
