### ISSUE TITLE
ENOENT: no such file or directory, lstat '$some/$projectdir/node_modules/validator'

### ISSUE THREAD

**Issue by jhg** [javascript-obfuscator/javascript-obfuscator#436]
After install JavascriptObfuscator, when call to obfuscate raise an error trying to lstat another node module.

**EDIT:** I have this issue running tests with `mock-fs`, I don't know why Javascript-Obfuscator need FS after require.

## Expected Behavior

Return obfuscated code.

## Current Behavior

Raise an error about lstat fail.

## Steps to Reproduce (for bugs)

1. run `npm install --save javascript-obfuscator`
2. use `mock-fs`
3. use it, for example:
```javascript
const javascriptObfuscator = require('javascript-obfuscator');
  console.log(src);
  src = javascriptObfuscator.obfuscate(src, {
    compact: false,
    controlFlowFlattering: false,
    deadCodeInjection: false,
    debugProtection: false,
    domainLock: [],
    renameGlobals: false,
    selfDefending: false,
    sourceMap: false,
    target: 'node',
    transformObjectKeys: false,
    unicodeEscapeSequence: false
  });
  console.log(src);
```

## Your Environment

* Obfuscator version used: javascript-obfuscator@0.18.3
* Node version used: v10.16.3

# Stack trace

     Error: ENOENT: no such file or directory, lstat '$some/$projectdir/node_modules/validator'
      at Object.realpathSync (fs.js:1461:7)                                                                             
      at toRealPath (internal/modules/cjs/loader.js:241:13)                                                             
      at tryFile (internal/modules/cjs/loader.js:237:22)                                                                
      at tryPackage (internal/modules/cjs/loader.js:218:10)                                                             
      at Function.Module._findPath (internal/modules/cjs/loader.js:339:18)                                              
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:633:25)                                       
      at Function.Module._load (internal/modules/cjs/loader.js:562:25)                                                  
      at Module.require (internal/modules/cjs/loader.js:692:17)                                                         
      at require (internal/modules/cjs/helpers.js:25:18)                                                                
      at new Validator (node_modules/class-validator/validation/Validator.js:48:28)                                     
      at class_1.get (node_modules/class-validator/container.js:14:51)                                                  
      at Object.getFromContainer (node_modules/class-validator/container.js:48:29)                                      
      at Object.validateSync (node_modules/class-validator/index.js:53:28)                                              
      at new e (node_modules/javascript-obfuscator/dist/index.js:24:188848)
      at _createInstance (node_modules/inversify/lib/resolution/instantiation.js:21:12)
      at Object.resolveInstance (node_modules/inversify/lib/resolution/instantiation.js:41:18)
      at $some/$projectdir/node_modules/inversify/lib/resolution/resolver.js:72:42
      at Array.map (<anonymous>)
      at Object.resolveInstance (node_modules/inversify/lib/resolution/instantiation.js:40:67)
      at $some/$projectdir/node_modules/inversify/lib/resolution/resolver.js:72:42
      at Array.map (<anonymous>)
      at Object.resolveInstance (node_modules/inversify/lib/resolution/instantiation.js:40:67)
      at $some/$projectdir/node_modules/inversify/lib/resolution/resolver.js:72:42
      at Object.resolve (node_modules/inversify/lib/resolution/resolver.js:96:12)
      at $some/$projectdir/node_modules/inversify/lib/container/container.js:320:37
      at Container._get (node_modules/inversify/lib/container/container.js:311:44)
      at Container.get (node_modules/inversify/lib/container/container.js:230:21)
      at e.value (node_modules/javascript-obfuscator/dist/index.js:24:21336)
      at Function.value (node_modules/javascript-obfuscator/dist/index.js:24:32223)
      at Object.module.exports [as encryptJsFile] (src/encryptJsFile.js:12:30)
      at Context.<anonymous> (test/test.js:28:9)

**Comment by jhg** [comment]
I found how to avoid errors between, maybe, some dynamic dependenceies and mocks for my current tests:
```javascript
    // NOTE: this is a hack for Javascript-Obfuscator load all dynamic dependencies before to mock fs
    javascriptObfuscator.obfuscate('true');
```
