### ISSUE TITLE
Error: Line 8: Unexpected character ' '

### ISSUE THREAD

**Issue by TuxOtaku** [javascript-obfuscator/javascript-obfuscator#445]
When running the CLI (regardless of command-line options), I get the following error:
```
/Users/ryandraga/.nvm/versions/node/v12.13.1/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/EspreeFacade.ts:100
        throw new Error(`Line ${position.line}: ${errorMessage}\n${formattedPointer} ${formattedCodeSlice}`);
              ^
Error: Line 8: Unexpected character '​'
> ...​...
```

## Your Environment

* Obfuscator version used: 0.18.6
* Node version used: 8.9.1 (also tried 12.13.1)

# Stack trace

 ```
   at Function.processParsingError (/Users/ryandraga/.nvm/versions/node/v8.9.1/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/EspreeFacade.ts:100:15)
    at Function.parse (/Users/ryandraga/.nvm/versions/node/v8.9.1/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/EspreeFacade.ts:44:46)
    at e.parseCode (/Users/ryandraga/.nvm/versions/node/v8.9.1/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscator.ts:155:29)
    at e.obfuscate (/Users/ryandraga/.nvm/versions/node/v8.9.1/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscator.ts:136:46)
    at Function.obfuscate (/Users/ryandraga/.nvm/versions/node/v8.9.1/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscatorFacade.ts:31:70)
    at Function.processSourceCodeWithoutSourceMap (/Users/ryandraga/.nvm/versions/node/v8.9.1/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/cli/JavaScriptObfuscatorCLI.ts:109:61)
    at e.apply (/Users/ryandraga/.nvm/versions/node/v8.9.1/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/cli/JavaScriptObfuscatorCLI.ts:410:37)
    at e.processSourceCode (/Users/ryandraga/.nvm/versions/node/v8.9.1/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/decorators/Initializable.ts:105:39)
    at e.apply (/Users/ryandraga/.nvm/versions/node/v8.9.1/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/cli/JavaScriptObfuscatorCLI.ts:372:18)
    at e.value (/Users/ryandraga/.nvm/versions/node/v8.9.1/lib/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/decorators/Initializable.ts:105:39)
```

**Comment by zamotkin** [comment]
This error literally means that you have Javascript error at line 8 of your code. It would help to find a bug if you share a fragment of your code including this line.
