### ISSUE TITLE
TypeScript Typing

### ISSUE THREAD

**Issue by yovanoc** [javascript-obfuscator/javascript-obfuscator#449]
follow up on that with more news: https://github.com/javascript-obfuscator/webpack-obfuscator/issues/58

## Expected Behavior

I think we should do some type unions instead of enums for this, or at least export them.

## Your Environment

* Obfuscator version used: I've just that in the project -> "webpack-obfuscator": "^0.18.3"
* Node version used: 13.3

# Stack trace
```
/Users/devchris/Documents/code/nodejs/project/node_modules/javascript-obfuscator/src/enums/ObfuscationTarget.ts:1
(function (exports, require, module, __filename, __dirname) { export enum ObfuscationTarget {
                                                              ^^^^^^

SyntaxError: Unexpected token 'export'
    at new Script (vm.js:87:7)
    at NativeCompileCache._moduleCompile (/Users/devchris/Documents/code/nodejs/project/packages/main/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/Users/devchris/Documents/code/nodejs/project/packages/main/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/devchris/Documents/code/nodejs/project/node_modules/ts-node/src/index.ts:529:44)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (/Users/devchris/Documents/code/nodejs/project/packages/main/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/devchris/Documents/code/nodejs/project/packages/main/webpack.config.ts:6:1)
    at Module._compile (/Users/devchris/Documents/code/nodejs/project/packages/main/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module.m._compile (/Users/devchris/Documents/code/nodejs/project/node_modules/ts-node/src/index.ts:536:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/devchris/Documents/code/nodejs/project/node_modules/ts-node/src/index.ts:539:12)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (/Users/devchris/Documents/code/nodejs/project/packages/main/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/Users/devchris/Documents/code/nodejs/project/packages/main/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/Users/devchris/Documents/code/nodejs/project/packages/main/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /Users/devchris/Documents/code/nodejs/project/packages/main/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/devchris/Documents/code/nodejs/project/packages/main/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at /Users/devchris/Documents/code/nodejs/project/packages/main/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/Users/devchris/Documents/code/nodejs/project/packages/main/node_modules/yargs/yargs.js:567:18)
    at /Users/devchris/Documents/code/nodejs/project/packages/main/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/Users/devchris/Documents/code/nodejs/project/packages/main/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
```

## Minimal working example that will help to reproduce issue
just a webpack.config.ts with these imports:

```ts
import { ObfuscationTarget } from "javascript-obfuscator/src/enums/ObfuscationTarget";
import { IdentifierNamesGenerator } from "javascript-obfuscator/src/enums/generators/identifier-names-generators/IdentifierNamesGenerator";
```

and this in plugins array:

```ts
new JavaScriptObfuscator(
      {
        rotateUnicodeArray: true,
        deadCodeInjection: true,
        compact: true,
        selfDefending: true,
        deadCodeInjectionThreshold: 0.1,
        reservedStrings: ["test"],
        target: ObfuscationTarget.Node,
        identifierNamesGenerator:
          IdentifierNamesGenerator.MangledIdentifierNamesGenerator
      },
      []
    )
```

**Comment by zamotkin** [comment]
@yovanoc Did you pass all [webpack in Typescript configuration steps](https://webpack.js.org/configuration/configuration-languages/)?

**Comment by yovanoc** [comment]
yes but that's not the problem here, I think is just because enums are not exported by webpack-obfuscator, and I have to load them by this package that is don't directly installed. We should replace these enums by type union I think like this to not have to import them

```ts
type IdentifierNamesGenerator = "mangled" | "hexadecimal";
```

**Comment by zamotkin** [comment]
How does it help with your issue: _SyntaxError: Unexpected token 'export'_?

**Comment by yovanoc** [comment]
that's because they are imported via `src` I think or something like that

**Comment by zamotkin** [comment]
I think that your suggestion is just a different code style. You have an error with your typescript webpack configuration, it cannot understand _export_ syntax. Please read [this thread](https://github.com/webpack/webpack/issues/5053), maybe it helps you.

**Comment by yovanoc** [comment]
No, all is working great with all others plugins I use. Here the problem is because these enums are not exported from the dist folder. So we can't use them

**Comment by zamotkin** [comment]
I have no idea how to help you.

**Comment by Zirpoo** [comment]
I think type unions would be simplier because you won't have to export enums to your config object.
You can already see the type to use when hovering with your mouse on the config property with intellisense anyway.

Something like this maybe

`type ObfuscationTarget = "browser" | "browser-no-eval" | "node";
type IdentifierNamesGenerator= "hexadecimal" | "mangled"";`

**Comment by sanex3339** [comment]
Will look into this on the holidays

**Comment by sanex3339** [comment]
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/473

Now, typings will correctly accept string values for enum-like options
Expect a release today

**Comment by sanex3339** [comment]
`0.20.3` is out

**Comment by yovanoc** [comment]
Oh nice man, but can you make a release of webpack-obfuscator please?

**Comment by sanex3339** [comment]
Hmm, looks like not fixed

**Comment by sanex3339** [comment]
I found the problem. Will release a new version soon

**Comment by sanex3339** [comment]
Should work now. Updated both `javascript-obfuscator` and `webpack-obfuscator` `to 0.20.4`

Please try and say if here any problems or not

**Comment by yovanoc** [comment]
Nope I got this error:


```
TypeError: Cannot read property 'type' of null
    at Function.isIdentifierNode (/Users/devchris/Documents/code/nodejs/project/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/node/NodeGuards.ts:160:21)
    at m.storeCatchClauseParam (/Users/devchris/Documents/code/nodejs/project/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/node-transformers/obfuscating-transformers/CatchClauseTransformer.ts:102:24)
    at m.transformNode (/Users/devchris/Documents/code/nodejs/project/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/node-transformers/obfuscating-transformers/CatchClauseTransformer.ts:88:14)
    at visitorFunction (/Users/devchris/Documents/code/nodejs/project/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/node-transformers/obfuscating-transformers/CatchClauseTransformer.ts:66:41)
    at Controller.<anonymous> (/Users/devchris/Documents/code/nodejs/project/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/node-transformers/TransformersRunner.ts:160:55)
    at Controller.__execute (/Users/devchris/Documents/code/nodejs/project/node_modules/estraverse/estraverse.js:330:31)
    at Controller.replace (/Users/devchris/Documents/code/nodejs/project/node_modules/estraverse/estraverse.js:570:27)
    at Object.replace (/Users/devchris/Documents/code/nodejs/project/node_modules/estraverse/estraverse.js:651:27)
    at l.transform (/Users/devchris/Documents/code/nodejs/project/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/node-transformers/TransformersRunner.ts:112:24)
    at o.runTransformationStage (/Users/devchris/Documents/code/nodejs/project/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscator.ts:233:40)
    at o.transformAstTree (/Users/devchris/Documents/code/nodejs/project/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscator.ts:184:24)
    at obfuscate (/Users/devchris/Documents/code/nodejs/project/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscator.ts:136:56)
    at Function.obfuscate (/Users/devchris/Documents/code/nodejs/project/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscatorFacade.ts:31:70)
    at WebpackObfuscator.obfuscate (/Users/devchris/Documents/code/nodejs/project/packages/cli/node_modules/webpack-obfuscator/dist/index.js:61:67)
    at /Users/devchris/Documents/code/nodejs/project/packages/cli/node_modules/webpack-obfuscator/dist/index.js:30:77
    at Set.forEach (<anonymous>)
    at /Users/devchris/Documents/code/nodejs/project/packages/cli/node_modules/webpack-obfuscator/dist/index.js:24:29
    at Set.forEach (<anonymous>)
    at /Users/devchris/Documents/code/nodejs/project/packages/cli/node_modules/webpack-obfuscator/dist/index.js:23:32
    at _next0 (eval at create (/Users/devchris/Documents/code/nodejs/project/packages/cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (/Users/devchris/Documents/code/nodejs/project/packages/cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at ForkTsCheckerWebpackPlugin.emitCallback (/Users/devchris/Documents/code/nodejs/project/node_modules/fork-ts-checker-webpack-plugin/src/index.ts:938:7)
    at emit (/Users/devchris/Documents/code/nodejs/project/node_modules/fork-ts-checker-webpack-plugin/src/index.ts:584:14)
    at Hook.eval [as callAsync] (eval at create (/Users/devchris/Documents/code/nodejs/project/packages/cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/devchris/Documents/code/nodejs/project/packages/cli/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.emitAssets (/Users/devchris/Documents/code/nodejs/project/packages/cli/node_modules/webpack/lib/Compiler.js:678:19)
    at /Users/devchris/Documents/code/nodejs/project/packages/cli/node_modules/webpack/lib/Compiler.js:370:10
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by sanex3339** [comment]
This is not related to typings.

Looks like you used try-catch without optional `catch` parameters

```
try {
} catch {}
```

**Comment by sanex3339** [comment]
Will create other issue for optional catch parameters.

If types now works correctly, i'll close this issue.

I need your approve

**Comment by yovanoc** [comment]
Nope, is just the webpack config that I call like that `webpack --config webpack.config.ts`:

```ts
import TsConfigPathsPlugin from "tsconfig-paths-webpack-plugin";
import ForkTsCheckerWebpackPlugin from "fork-ts-checker-webpack-plugin";
import path from "path";
import webpack from "webpack";
import SentryWebpackPlugin from "@sentry/webpack-plugin";
import pkg from "./package.json";
import JavaScriptObfuscator from "webpack-obfuscator";

const config: webpack.Configuration = {
  devtool: "source-map",
  entry: "./src/index.ts",
  mode: "production",
  module: {
    rules: [
      {
        exclude: /node_modules/,
        test: /\.tsx?$/,
        use: [
          {
            loader: "ts-loader",
            options: {
              reportFiles: ["src/**/*.{ts,tsx}"],
              configFile: "tsconfig.prod.json",
              projectReferences: true,
              // disable type checker - we will use it in fork plugin
              transpileOnly: true
            }
          }
        ]
      },
      {
        enforce: "pre",
        exclude: /node_modules/,
        test: /\.tsx?$/,
        use: [
          {
            loader: "eslint-loader",
            options: {
              quiet: true
            }
          }
        ]
      }
    ]
  },
  optimization: {
    // minimize: false,
    removeEmptyChunks: true
  },
  output: {
    filename: "cli.js",
    path: path.resolve(__dirname, "dist")
  },
  resolve: {
    extensions: [".tsx", ".ts", ".js"],
    plugins: [new TsConfigPathsPlugin()]
  },
  plugins: [
    new ForkTsCheckerWebpackPlugin(),
    new SentryWebpackPlugin({
      include: "./dist",
      release: `cli@${pkg.version}`,
      ignoreFile: ".sentrycliignore",
      ignore: ["node_modules", "webpack.config.ts"],
      configFile: "sentry.properties"
    }),
    new JavaScriptObfuscator(
      {
        rotateUnicodeArray: true,
        deadCodeInjection: true,
        compact: true,
        selfDefending: true,
        deadCodeInjectionThreshold: 0.1,
        target: "node",
        identifierNamesGenerator: "mangled"
      },
      []
    )
  ],
  target: "node"
};

export default config;
```

**Comment by yovanoc** [comment]
But yeah types are good now you're right

**Comment by sanex3339** [comment]
Error with `TypeError: Cannot read property 'type' of null` is not related to your config.
This error is about your source code that you are trying to obfuscate.

Somewhere in your code catch-clause statement without optional catch parameters is exist:

```
try {
} catch {}
```

Currently, obfuscator not support optional catch parameters, so will try to fix this.

**Comment by sanex3339** [comment]
Ok. If types are good will close this issue.

**Comment by yovanoc** [comment]
Oh yes my bad, I was elsewhere ^^
You are right, typescript support that now.

**Comment by sanex3339** [comment]
https://github.com/javascript-obfuscator/javascript-obfuscator/issues/475
