### ISSUE TITLE
Maximum call stack size exceeded using transformObjectKeys

### ISSUE THREAD

**Issue by beeing** [javascript-obfuscator/javascript-obfuscator#512]
Running this with `transformObjectKeys` will causes the error.

```
const v = `test: ${doSomething(obj, { tag: 'data' })}`;
```

## Steps to Reproduce

1. Paste the above code to https://obfuscator.io
2. Tick Transform Object Keys
3. Click Obfuscate

## Your Environment

* Obfuscator version used: latest
* Node version used: v12.13.0

# Stack trace
```
JavaScriptObfuscator/src/node/NodeStatementUtils.ts:45
    public static getRootStatementOfNode (node: ESTree.Node): ESTree.Statement {
           ^
RangeError: Maximum call stack size exceeded
    at Function.getRootStatementOfNode (JavaScriptObfuscator/src/node/NodeStatementUtils.ts:45:12)
    at Function.getRootStatementOfNode (JavaScriptObfuscator/src/node/NodeStatementUtils.ts:57:39)
    at Function.getRootStatementOfNode (JavaScriptObfuscator/src/node/NodeStatementUtils.ts:57:39)
    at Function.getRootStatementOfNode (JavaScriptObfuscator/src/node/NodeStatementUtils.ts:57:39)
    at Function.getRootStatementOfNode (JavaScriptObfuscator/src/node/NodeStatementUtils.ts:57:39)
    at Function.getRootStatementOfNode (JavaScriptObfuscator/src/node/NodeStatementUtils.ts:57:39)
    at Function.getRootStatementOfNode (JavaScriptObfuscator/src/node/NodeStatementUtils.ts:57:39)
    at Function.getRootStatementOfNode (JavaScriptObfuscator/src/node/NodeStatementUtils.ts:57:39)
    at Function.getRootStatementOfNode (JavaScriptObfuscator/src/node/NodeStatementUtils.ts:57:39)
```

**Comment by sanex3339** [comment]
Thank you, will fix it this week

**Comment by sanex3339** [comment]
Will fixed in https://github.com/javascript-obfuscator/javascript-obfuscator/issues/512
Expect a release in a few days
