### ISSUE TITLE
function default parameters problem

### ISSUE THREAD

**Issue by topm01** [javascript-obfuscator/javascript-obfuscator#519]
Hi thanks for create this great project
does any one know why function default parameters not work
when use function default parameters will cause error

## Expected Behavior
 should work (ES2015)

## Current Behavior
Crash

## Steps to Reproduce
1. create a function with default parameters then will happen
 

## Your Environment

* Obfuscator version used: 0.23.2 release
* Node version used:  8.17.0

# Stack trace
Error: @postConstruct error in class o: Illegal argument undefined
    at _postConstruct (node_modules/inversify/lib/resolution/instantiation.js:30:19)
    at Object.resolveInstance (node_modules/inversify/lib/resolution/instantiation.js:47:5)
    at node_modules/inversify/lib/resolution/resolver.js:72:42
    at Array.map (<anonymous>)
    at Object.resolveInstance (node_modules/inversify/lib/resolution/instantiation.js:40:67)
    at node_modules/inversify/lib/resolution/resolver.js:72:42
    at Object.resolve (node_modules/inversify/lib/resolution/resolver.js:96:12)
    at node_modules/inversify/lib/container/container.js:319:37
    at Container._get (node_modules/inversify/lib/container/container.js:310:44)
    at Container.get (node_modules/inversify/lib/container/container.js:230:21)

## Minimal working example that will help to reproduce issue
function abc(d= ''){
}

**Comment by sanex3339** [comment]
Cannot reproduce here:
https://obfuscator.io/

**Comment by topm01** [comment]
Sorry my fault , i just pass wrong code to javascript-obfuscator , it work now!!
Thanks
