### ISSUE TITLE
TypeError: Cannot read property 'defs' of undefined

### ISSUE THREAD

**Issue by cobrowse-enterprise** [javascript-obfuscator/javascript-obfuscator#535]
Obfuscation crashes when run via webpack-obfuscator (stack trace below) with latest version (0.24.2)

Reverting to 0.23.2 fixes issue.

## Your Environment
* Obfuscator version used: 0.24.2
* Node version used: 13.6.0

# Stack trace
```
TypeError: Cannot read property 'defs' of undefined
    at find (/usr/src/app/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/analyzers/scope-analyzer/ScopeAnalyzer.ts:76:72)
    at Array.find (<anonymous>)
    at forEach (/usr/src/app/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/analyzers/scope-analyzer/ScopeAnalyzer.ts:74:22)
    at Array.forEach (<anonymous>)
    at o.sanitizeScopes (/usr/src/app/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/analyzers/scope-analyzer/ScopeAnalyzer.ts:71:27)
    at o.sanitizeScopes (/usr/src/app/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/analyzers/scope-analyzer/ScopeAnalyzer.ts:84:18)
    at o.acquireScope (/usr/src/app/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/analyzers/scope-analyzer/ScopeAnalyzer.ts:67:14)
    at o.transformNode (/usr/src/app/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/node-transformers/obfuscating-transformers/ScopeIdentifiersTransformer.ts:61:48)
    at visitorFunction (/usr/src/app/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/node-transformers/obfuscating-transformers/ScopeIdentifiersTransformer.ts:49:41)
    at Controller.<anonymous> (/usr/src/app/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/node-transformers/TransformersRunner.ts:98:39)
    at Controller.__execute (/usr/src/app/node_modules/estraverse/estraverse.js:330:31)
    at Controller.replace (/usr/src/app/node_modules/estraverse/estraverse.js:570:27)
    at Object.replace (/usr/src/app/node_modules/estraverse/estraverse.js:651:27)
    at N.transform (/usr/src/app/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/node-transformers/TransformersRunner.ts:73:24)
    at o.runTransformationStage (/usr/src/app/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscator.ts:103:40)
    at o.transformAstTree (/usr/src/app/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscator.ts:82:24)
    at obfuscate (/usr/src/app/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscator.ts:51:40)
    at Function.obfuscate (/usr/src/app/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscatorFacade.ts:12:53)
    at WebpackObfuscator.obfuscate (/usr/src/app/node_modules/webpack-obfuscator/dist/index.js:61:67)
    at /usr/src/app/node_modules/webpack-obfuscator/dist/index.js:30:77
    at Array.forEach (<anonymous>)
    at /usr/src/app/node_modules/webpack-obfuscator/dist/index.js:24:29
    at Array.forEach (<anonymous>)
    at /usr/src/app/node_modules/webpack-obfuscator/dist/index.js:23:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/src/app/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.emitAssets (/usr/src/app/node_modules/webpack/lib/Compiler.js:491:19)
    at onCompiled (/usr/src/app/node_modules/webpack/lib/Compiler.js:278:9)
    at /usr/src/app/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/src/app/node_modules/tapable/lib/Hook.js:154:20)
    at /usr/src/app/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/usr/src/app/node_modules/tapable/lib/Hook.js:154:20)
    at /usr/src/app/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
```

**Comment by sanex3339** [comment]
Interesting. Will see

**Comment by sanex3339** [comment]
Can you try to reproduce it with the minimum code size?

**Comment by jeromewir** [comment]
We had the same error yesterday with our codebase too, tried to understand what was going on and pin pointed the issue in this line:
https://github.com/javascript-obfuscator/javascript-obfuscator/blob/da3c0802b2a41de8f3aa14e22e594dc21f97f832/src/analyzers/scope-analyzer/ScopeAnalyzer.ts#L132

`childScope.variables[0]` was an empty array so `classNameVariable` was undefined

I didn't understand what was causing this error though.

**Comment by sanex3339** [comment]
Will fix it today.

**Comment by sanex3339** [comment]
Problem with class expressions
```
const v = class {}
```

**Comment by sanex3339** [comment]
Expect a new release in an hour or so

**Comment by sanex3339** [comment]
Released as `0.24.3`

**Comment by sanex3339** [comment]
Create a new issue or write here if you will have the same problem

**Comment by cobrowse-enterprise** [comment]
Fixed for me, thanks for such a quick response!

**Comment by jeromewir** [comment]
Confirmed working for me too with `0.24.3`, thanks a lot for the quick fix!
