### ISSUE TITLE
Screen keeps white after using --disable-console-output

### ISSUE THREAD

**Issue by cacorot** [javascript-obfuscator/javascript-obfuscator#600]
Hello, friend
I encounter this problem after using '--disable-console-output'

Cannot read property 'console' of undefined
TypeError: Cannot read property 'console' of undefined
    at http://127.0.0.1:22926/appservice/app.js:27:18
    at _0xe1942e (http://127.0.0.1:22926/appservice/app.js:18:52)
    at http://127.0.0.1:22926/appservice/app.js:34:4
    at require (http://127.0.0.1:22926/appservice/__dev__/WAService.js:2:1787917)
    at <anonymous>:1:1
    at doWhenAllScriptLoaded (http://127.0.0.1:22926/appservice/appservice?t=1588145689741:1292:21)
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:22926/appservice/appservice?t=1588145689741:1304:5)
    at HTMLScriptElement.script.onload (http://127.0.0.1:22926/appservice/appservice?t=1588145689741:1312:20)

My demo project is a 'wechat' programe. 

[app.zip](https://github.com/javascript-obfuscator/javascript-obfuscator/files/4550347/app.zip)

Thank you for your help!

**Comment by cacorot** [comment]
var b = function () {
    var c = !![];
    return function (d, e) {
        var f = c ? function () {
            if (e) {
                var g = e['apply'](d, arguments);
                e = null;
                return g;
            }
        } : function () {
        };
        c = ![];
        return f;
    };
}();
var a = b(this, function () {
    var c = function () {
    };
    var d = function () {
        var f;
        try {
            f = Function('return\x20(function()\x20' + '{}.constructor(\x22return\x20this\x22)(\x20)' + ');')();
        } catch (g) {
            f = window;
        }
        return f;
    };
    var e = d();
    if (!e['console']) {
        e['console'] = function (f) {
            var g = {};
            g['log'] = f;
            g['warn'] = f;
            g['debug'] = f;
            g['info'] = f;
            g['error'] = f;
            g['exception'] = f;
            g['table'] = f;
            g['trace'] = f;
            return g;
        }(c);
    } else {
        e['console']['log'] = c;
        e['console']['warn'] = c;
        e['console']['debug'] = c;
        e['console']['info'] = c;
        e['console']['error'] = c;
        e['console']['exception'] = c;
        e['console']['table'] = c;
        e['console']['trace'] = c;
    }
});
a();
var numAi = 0x0;
var timer;
Page({
    'data': {
        'btnState': ![],
        'winNum': 0x0,
        'gameOfPlay': '',
        'imageUserScr': '/pages/image/wenhao.png',
        'imageAiScr': '',
        'srcs': [
            '/pages/image/shitou.png',
            '/pages/image/jiandao.png',
            '/pages/image/bu.png'
        ]
    },
    'onLoad': function () {
        var c = wx['getStorageSync']('winNum');
        if (c != null && c != '') {
            this['data']['winNum'] = c;
        }
        this['timerGo']();
    },
    'changeForChoose'(c) {
        console['log']('123');
        if (this['data']['btnState'] == !![]) {
            return;
        }
        this['setData']({ 'imageUserScr': this['data']['srcs'][c['currentTarget']['id']] });
        clearInterval(timer);
        var d = this['data']['imageUserScr'];
        var f = this['data']['imageAiScr'];
        var g = this['data']['winNum'];
        var h = '0.0~\x0aYou\x20Lost!';
        if (d == '/pages/image/shitou.png' && f == '/pages/image/jiandao.png') {
            g++;
            h = 'Ho~\x0aYou\x20Win!';
            wx['setStorageSync']('winNum', g);
        }
        ;
        if (d == '/pages/image/jiandao.png' && f == '/pages/image/bu.png') {
            g++;
            h = 'Ho~\x0aYou\x20Win!';
            wx['setStorageSync']('winNum', g);
        }
        ;
        if (d == '/pages/image/bu.png' && f == '/pages/image/shitou.png') {
            g++;
            h = 'Ho~\x0aYou\x20Win!';
            wx['setStorageSync']('winNum', g);
        }
        ;
        if (d == f) {
            h = 'Game\x20Draw!';
        }
        this['setData']({
            'winNum': g,
            'gameOfPlay': h,
            'btnState': !![]
        });
    },
    'timerGo'() {
        timer = setInterval(this['move'], 0x64);
    },
    'move'() {
        if (numAi >= 0x3) {
            numAi = 0x0;
        }
        this['setData']({ 'imageAiScr': this['data']['srcs'][numAi] });
        numAi++;
    },
    'again'() {
        if (this['data']['btnState'] == ![]) {
            return;
        }
        this['timerGo']();
        this['setData']({
            'btnState': ![],
            'gameOfPlay': '',
            'imageUserScr': '/pages/image/wenhao.png'
        });
    }
});

**Comment by cacorot** [comment]
interface Function {
    /**
     * Returns the name of the function. Function names are read-only and can not be changed.
     */
    readonly name: string;
}


It seems 'Function' is defined by this....Maybe doesn't support your sentence 
' Function('return\x20(function()\x20' + '{}.constructor(\x22return\x20this\x22)(\x20)' + ');')();'

**Comment by cacorot** [comment]
I‘m wondering why not using this 
"
var a = b(this, function () {
    var c = function () {
    };
    var d = function () {
        return console;
    };
    var e = d();
    e['log'] = c;
    e['warn'] = c;
    e['debug'] = c;
    e['info'] = c;
    e['error'] = c;
    e['exception'] = c;
    e['table'] = c;
    e['trace'] = c;
});
a();

"
