### ISSUE TITLE
JavascriptObfuscator crashes when used in Jest environment

### ISSUE THREAD

**Issue by Wain-PC** [javascript-obfuscator/javascript-obfuscator#63]
Hello! This one is really strange.
I've tried to run some unit tests for [gulp-javascript-obfuscator](https://github.com/javascript-obfuscator/gulp-javascript-obfuscator) using Jest and instantly found that my unit tests fail for no apparent reason (working like a charm in Mocha in the same time with the exact same test code).

I've managed to boil down the issue to the following lines:
```javascript
const JavaScriptObfuscator = require('javascript-obfuscator');

describe('JavaScriptObfuscator', function () {
	it('should definitely succeed', ()=> {
		const obfuscationResult = JavaScriptObfuscator.obfuscate(`alert('Hello, world!')`,{});
	});
});
```
**Output for *mocha*:**
```
javascriptObfuscator()
    √ should definitely succeed (116ms)

  1 passing (122ms)
```

**Output for *jest*:**
```
FAIL  test\test.js
  ● javascriptObfuscator() › should definitely succeed

    Cannot read property 'constructor' of null

      at _createSubRequests (node_modules/inversify/lib/planning/planner.js:106:19)
      at Object.plan (node_modules/inversify/lib/planning/planner.js:125:5)
      at node_modules/inversify/lib/container/container.js:218:37
      at Container.Object.<anonymous>.Container._get (node_modules/inversify/lib/container/container.js:211:44)
      at Container.Object.<anonymous>.Container.get (node_modules/inversify/lib/container/container.js:176:21)
      at InversifyContainerFacade.get (node_modules/javascript-obfuscator/dist/index.js:2647:35)
      at Function.obfuscate (node_modules/javascript-obfuscator/dist/index.js:1302:65)
      at Object.it (test/test.js:5:50)

  javascriptObfuscator()
    × should definitely succeed (4389ms)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        5.316s
Ran all test suites.

```

**Comment by sanex3339** [comment]
Error related to Inversify.js

**Comment by Wain-PC** [comment]
I've tried to manually reproduce the issue replicating your code:
```javascript
	const Container = require('inversify').Container;

	describe('inversify Container()', function () {

		it('should definitely succeed', () => {
			class Test {
				constructor() {
					this.container = new Container();
				}
			}

			const result = new Test();
			expect(result.container).not.toEqual(null);
		});
	});
```
 This test actually succeeds. Are there any more clues what might be going on?

**Comment by Wain-PC** [comment]
Would you mind creating a minimal working example for Inversify? I've traced it down to something like this:
```javascript
import {Container} from 'inversify';

const container = new Container();

container.get(smth); //Stuck here, what to get to reproduce the issue? I guess, we should put something to it beforehand.
```

I've had no actual experience with Inversify, so that's all I could come with as of now.
I'll fill in the bug on the Inversify.js repo if I'll get the reproduction steps.
Thanks in advance!

**Comment by sanex3339** [comment]
Please, check his readme. It's full of examples.

**Comment by sanex3339** [comment]
For example https://github.com/inversify/InversifyJS#the-basics

**Comment by sanex3339** [comment]
Any news?

**Comment by Wain-PC** [comment]
Sorry, no time to investigate further yet. However, thanks for the docs link, I've already checked them! I'd be able to continue in a few days.

**Comment by sanex3339** [comment]
Closed due inactivity. Please, recreate issue if you want.
