### ISSUE TITLE
Error in InversifyContainerFacade 

### ISSUE THREAD

**Issue by cameronbraid** [javascript-obfuscator/javascript-obfuscator#679]
```
#15 453.8 ERROR in ./src/nitro/types/searchKey.js
#15 453.8 Module build failed (from ./node_modules/obfuscator-loader/lib/index.js):
#15 453.8 Error: The number of constructor arguments in the derived class t must be >= than the number of constructor arguments of its base class.
#15 453.8     at getTargets (/build/node_modules/inversify/lib/planning/reflection_utils.js:33:15)
#15 453.8     at Object.getDependencies (/build/node_modules/inversify/lib/planning/reflection_utils.js:11:19)
#15 453.8     at /build/node_modules/inversify/lib/planning/planner.js:106:51
#15 453.8     at Array.forEach (<anonymous>)
#15 453.8     at _createSubRequests (/build/node_modules/inversify/lib/planning/planner.js:94:20)
#15 453.8     at /build/node_modules/inversify/lib/planning/planner.js:108:17
#15 453.8     at Array.forEach (<anonymous>)
#15 453.8     at /build/node_modules/inversify/lib/planning/planner.js:107:26
#15 453.8     at Array.forEach (<anonymous>)
#15 453.8     at _createSubRequests (/build/node_modules/inversify/lib/planning/planner.js:94:20)
#15 453.8     at Object.plan (/build/node_modules/inversify/lib/planning/planner.js:129:9)
#15 453.8     at /build/node_modules/inversify/lib/container/container.js:316:37
#15 453.8     at Container._get (/build/node_modules/inversify/lib/container/container.js:309:44)
#15 453.8     at Container.getTagged (/build/node_modules/inversify/lib/container/container.js:231:21)
#15 453.8     at Container.getNamed (/build/node_modules/inversify/lib/container/container.js:234:21)
#15 453.8     at e.nodeTransformerFactory (/build/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/container/InversifyContainerFacade.ts:75:61)
#15 453.8     at e.value (/build/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/node-transformers/TransformersRunner.ts:60:50)
#15 453.8     at e.value (/build/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscator.ts:236:49)
#15 453.8     at e.value (/build/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscator.ts:173:46)
#15 453.8     at e.value (/build/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscator.ts:138:72)
#15 453.8     at Function.value (/build/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/JavaScriptObfuscatorFacade.ts:27:85)
#15 453.8     at Object.obfuscator (/build/node_modules/obfuscator-loader/lib/index.js:47:50)

```

the searchKey.js is a simple single function 

```
function k(a,b,c) {
 some string concat and calls to a, b and c
}
module.exports = {
	k,
}
```

## Your Environment
obfuscator-loader: 1.1.2
javascript-obfuscator: 0.15.0
webpack 4.41.2

* Node version used:
v12.18.2

**Comment by sanex3339** [comment]
Hi. Update to the latest `1.7.0` version

**Comment by cameronbraid** [comment]
That was quick !  I only installed obfuscator-loader yesterday.

Ok, i'll give it a try

**Comment by sanex3339** [comment]
You have to update `javascript-obfuscator` to the 1.7.0 version

**Comment by cameronbraid** [comment]
ok, you should look to update `obfuscator-loader` to use the latest version. I never directly installed `javascript-obfuscator`

**Comment by sanex3339** [comment]
I don't responsible for `obfuscator-loader`. You can create the PR to this library.

**Comment by cameronbraid** [comment]
Upgraded to `javascript-obfuscator` 1.7.0 and get the same problem

**Comment by cameronbraid** [comment]
I tried my searchKey.js at https://www.obfuscator.io/ and it works there.

So could it be some other dependency conflict ?

**Comment by sanex3339** [comment]
> Upgraded to `javascript-obfuscator` 1.7.0 and get the same problem

1.7.0 cannot have this problem. So something with your dependencies.

**Comment by cameronbraid** [comment]
Ok, its probbaly the dep in obfuscator-loader.. needs to change to a peer dep
