### ISSUE TITLE
Dynamic import and Vue cannot be used with webpack loader

### ISSUE THREAD

**Issue by sxzz** [javascript-obfuscator/javascript-obfuscator#711]
Code: 
```javascript

// index.js
async function main() {
  const mod = await import("./module");
  console.log(mod);
}
main();

// module.js
export const text = "Hello World";
```

Error:
```
ERROR in ./src/index.js
Module build failed (from (webpack)-obfuscator/dist/loader/index.js):
Error: SyntaxError: Unexpected token (2:20)
    at Function.parseCode (/Users/kevin/projects/webpack-obfuscator-demo/node_modules/webpack-obfuscator/dist/loader/index.js:63:23)
    at Function.getCommentedSource (/Users/kevin/projects/webpack-obfuscator-demo/node_modules/webpack-obfuscator/dist/loader/index.js:31:55)
    at Object.Loader (/Users/kevin/projects/webpack-obfuscator-demo/node_modules/webpack-obfuscator/dist/loader/index.js:84:63)
```

Webpack config:
```javascript
// webpack.config.js
const path = require("path");
const WebpackObfuscator = require("webpack-obfuscator");

module.exports = {
  mode: "production",
  module: {
    rules: [
      {
        test: /\.js$/,
        include: [path.resolve(".", "src")],
        enforce: "post",
        use: {
          loader: WebpackObfuscator.loader,
          options: {
            rotateStringArray: true,
          },
        },
      },
    ],
  },
};
```

**Comment by sanex3339** [comment]
PR for literals

**Comment by sanex3339** [comment]
PR for `escodegen`
https://github.com/estools/escodegen/pull/420

**Comment by sanex3339** [comment]
`1.10.2` has been released with fixed `sources` of exports. Now these exports won't be moved to the `StringArray` or splitted by `splitStrings` option.

Support of named `export * as` is covered by this issue:
https://github.com/javascript-obfuscator/javascript-obfuscator/issues/710

I'll close this issue in favor of https://github.com/javascript-obfuscator/javascript-obfuscator/issues/710
