### ISSUE TITLE
Getting TypeError (ERR_INVALID_ARG_TYPE) when trying to import after obfuscation

### ISSUE THREAD

**Issue by zaidabuhijlehWindward** [javascript-obfuscator/javascript-obfuscator#766]
This is what my file structure looks like: (see "scripts"/"dev" in package.json to see my obfuscation command)
![image](https://user-images.githubusercontent.com/68923467/94495103-20bb1180-01ae-11eb-98f3-e2dae0a84623.png)
So I compile my typescript to JS into the dist directory. I then obfuscate all the JS in the dist directory and output is directed to dist-obfu directory. I then publish the dist-obfu directory. This is how the file structure is when i install from npm:
![image](https://user-images.githubusercontent.com/68923467/94495315-a939b200-01ae-11eb-90e9-e675f353a03b.png)

I import the package as follows: (this is how node told me to import)
import pkg from 'windwardclient';
const {WindwardClient} = pkg;

when I try to run the code, I get:
PS C:\Users\Zaid\Desktop\HERE> node .\test.js
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of URL. Received undefined
    at fileURLToPath (internal/url.js:1347:11)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:751:21)
    at Loader.resolve (internal/modules/esm/loader.js:82:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:226:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Am I doing anything wrong? Thanks!

**Comment by zaidabuhijlehWindward** [comment]
This is my src/index.ts:
![image](https://user-images.githubusercontent.com/68923467/94495498-30872580-01af-11eb-9e49-6df7dbbf8846.png)

And this is my dist/index.js after compiling:
![image](https://user-images.githubusercontent.com/68923467/94495542-4f85b780-01af-11eb-89b6-327c24a89a06.png)

and this is my dist-obfu/index.js after obfuscation:
![image](https://user-images.githubusercontent.com/68923467/94495688-a55a5f80-01af-11eb-90e2-cfa200023464.png)

Im not sure what the source of the problem is, but when i publish un-obfuscated code it works perfectly, but doesnt when i obfuscate and publish. Let me know if you need more info and thanks for the help!

**Comment by zaidabuhijlehWindward** [comment]
I ended up fixing by fixing some other things in my file structure.
