### ISSUE TITLE
Error when obfuscating TypeScript with deadCodeInjection: true

### ISSUE THREAD

**Issue by msheakoski** [javascript-obfuscator/javascript-obfuscator#78]
Using webpack-obfuscator 0.10.1 (also with 0.10.0), I receive the following error when running `webpack -p`. It only occurs when deadCodeInjection is turned on and happens at any deadCodeInjectionThreshold. I'm not sure if it's my specific setup or an issue with javascript/webpack-obfuscator.

```
./node_modules/javascript-obfuscator/dist/webpack:/src/node/NodeUtils.ts:52
                .keys(node)
                     ^
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at e (./node_modules/javascript-obfuscator/dist/webpack:/src/node/NodeUtils.ts:52:22)
    at Array.map (native)
    at ./node_modules/javascript-obfuscator/dist/webpack:/src/node/NodeUtils.ts:62:48
    at Array.forEach (native)
    at e (./node_modules/javascript-obfuscator/dist/webpack:/src/node/NodeUtils.ts:54:25)
    at Array.map (native)
    at ./node_modules/javascript-obfuscator/dist/webpack:/src/node/NodeUtils.ts:62:48
    at Array.forEach (native)
    at e (./node_modules/javascript-obfuscator/dist/webpack:/src/node/NodeUtils.ts:54:25)
    at ./node_modules/javascript-obfuscator/dist/webpack:/src/node/NodeUtils.ts:64:53
    at Array.forEach (native)
    at e (./node_modules/javascript-obfuscator/dist/webpack:/src/node/NodeUtils.ts:54:25)
    at Array.map (native)
    at ./node_modules/javascript-obfuscator/dist/webpack:/src/node/NodeUtils.ts:62:48
    at Array.forEach (native)
    at e (./node_modules/javascript-obfuscator/dist/webpack:/src/node/NodeUtils.ts:54:25)
    at Array.map (native)
    at ./node_modules/javascript-obfuscator/dist/webpack:/src/node/NodeUtils.ts:62:48
    at Array.forEach (native)
    at e (./node_modules/javascript-obfuscator/dist/webpack:/src/node/NodeUtils.ts:54:25)
    at Array.map (native)
    at ./node_modules/javascript-obfuscator/dist/webpack:/src/node/NodeUtils.ts:62:48
    at Array.forEach (native)
    at e (./node_modules/javascript-obfuscator/dist/webpack:/src/node/NodeUtils.ts:54:25)
    at ./node_modules/javascript-obfuscator/dist/webpack:/src/node/NodeUtils.ts:64:53
    at Array.forEach (native)
    at e (./node_modules/javascript-obfuscator/dist/webpack:/src/node/NodeUtils.ts:54:25)
    at Array.map (native)
    at ./node_modules/javascript-obfuscator/dist/webpack:/src/node/NodeUtils.ts:62:48
```

**Comment by sanex3339** [comment]
Interesting , can you attach your source code or simple project  that can reproduce this error?

**Comment by msheakoski** [comment]
@sanex3339 I distilled the error down to what I believe is TypeScript's handling of async/await inside of a try/catch when targeting ES5 as the compilation language. Please see this repo for the example that I made:

https://github.com/msheakoski/javascript-obfuscator-example

**Comment by sanex3339** [comment]
Oh, catch it!

This construction thows error:
```
_a.trys.push([0, 2, , 3]);
```

In ast tree empty array element parsed as `null` and i don't expect this behaviour. 
I'll release 0.10.2 in a hour or so.

**Comment by sanex3339** [comment]
Fixed! Please check new `javascript-obfuscator@0.10.2` and `webpack-obfuscator@0.10.2`.

**Comment by msheakoski** [comment]
@sanex3339 I tested it out and the error no longer occurs during webpack compilation. The generated JavaScript appears to run without any visible issues in Chrome. Thank you! 👏👏👏

**Comment by sanex3339** [comment]
You're welcome.
