### ISSUE TITLE
Error when enable sourceMap

### ISSUE THREAD

**Issue by jianweiqin** [javascript-obfuscator/javascript-obfuscator#817]
When I set sourceMap to true, also sourceMapBaseUrl and sourceMapFileName are set, it raise an error. Please see the stack trace below. This happens when I input a directory.

## Your Environment

* Obfuscator version used:2.9.1
* Node version used:14.8

# Stack trace
Error: EEXIST: file already exists, mkdir 'C:\.mount\ssda2\nodejs\tests\mssqlTest\dist\obfuscated\core\djs'
    at Object.mkdirSync (fs.js:947:3)
    at mkdirpNativeSync (C:\.mount\sdb1\x65\UserProfile\AppData\Roaming\npm\node_modules\javascript-obfuscator\node_modules\mkdirp\lib\mkdirp-native.js:29:10)
    at Object.sync (C:\.mount\sdb1\x65\UserProfile\AppData\Roaming\npm\node_modules\javascript-obfuscator\node_modules\mkdirp\index.js:21:7)
    at t.ObfuscatedCodeWriter.writeFile (C:\.mount\sdb1\x65\UserProfile\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\cli\utils\ObfuscatedC
odeWriter.ts:98:16)
    at P.apply (C:\.mount\sdb1\x65\UserProfile\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\cli\JavaScriptObfuscatorCLI.ts:207:39)
    at P.processSourceCodeWithSourceMap (C:\.mount\sdb1\x65\UserProfile\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\decorators\Initializa
ble.ts:61:39)
    at P.apply (C:\.mount\sdb1\x65\UserProfile\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\cli\JavaScriptObfuscatorCLI.ts:190:18)
    at P.processSourceCode (C:\.mount\sdb1\x65\UserProfile\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\decorators\Initializable.ts:61:39)
    at C:\.mount\sdb1\x65\UserProfile\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\cli\JavaScriptObfuscatorCLI.ts:177:22
    at Array.forEach (<anonymous>)

**Comment by sanex3339** [comment]
Please, provide more info about how to reproduce this.

**Comment by jianweiqin** [comment]
jso.json:
>	"sourceMap": true,
>	"sourceMapBaseUrl": "http://localhost:3333",
>	"sourceMapFileName": "a",
>	"sourceMapMode": "separate",

command-line:
>javascript-obfuscator ./d.js --config jso.json

**Comment by jianweiqin** [comment]
> Please, provide more info about how to reproduce this.

jso.json:

>"sourceMap": true,
>"sourceMapBaseUrl": "http://localhost:3333",
>"sourceMapFileName": "a",
>"sourceMapMode": "separate",

command-line:

>javascript-obfuscator ./d.js --config jso.json

**Comment by jianweiqin** [comment]
@sanex3339 

jso.json:

>"sourceMap": true,
>"sourceMapBaseUrl": "http://localhost:3333",
>"sourceMapFileName": "a",
>"sourceMapMode": "separate",

command-line:

>javascript-obfuscator ./d.js --config jso.json

**Comment by jianweiqin** [comment]
@sanex3339 
jso.json:

>"sourceMap": true,
>"sourceMapBaseUrl": "http://localhost:3333",
>"sourceMapFileName": "a",
>"sourceMapMode": "separate",

command-line:

>javascript-obfuscator ./dir --config jso.json

**Comment by sanex3339** [comment]
Cannot reproduce with the following options.
For me it works fine.

**Comment by jianweiqin** [comment]
It seems work fine after your fixing #816. But I have another problem. When I input a directory:
> javascript-obfuscator ./a --config ./jso.json

jso.json:
>"sourceMap": true,
>"sourceMapBaseUrl": "http://localhost:3333",
>"sourceMapFileName": "aaa",
>"sourceMapMode": "separate",

The output .map file only contains the infomation of the last js file of that directory.
![33333](https://user-images.githubusercontent.com/26958373/100075217-a55aa100-2e7a-11eb-966c-65e46652d044.png)

**Comment by sanex3339** [comment]
Because you have to set different source map file names for each source `.js` file.

**Comment by jianweiqin** [comment]
@sanex3339 
No. Only one config file 'jso.json' and only one 'sourceMapFileName' setting in that config file and only one command line, AND, there are two files in the directory but only one output .map file.

>javascript-obfuscator ./a --config ./jso.json

jso.json:

>"sourceMap": true,
>"sourceMapBaseUrl": "http://localhost:3333",
>"sourceMapFileName": "aaa",
>"sourceMapMode": "separate",

**Comment by sanex3339** [comment]
Don't use `sourceMapFileName` option. Without it source map file names will be the same as source `.js` file names.

**Comment by sanex3339** [comment]
Seems i have to add a prefix to the `sourceMapFileName` for a directory obfuscation

**Comment by jianweiqin** [comment]
OK. I see. But this can be improved. You are using 'sources' and 'sourcesContent' in the .map file, which are both arrays that can contains multi elements.

**Comment by sanex3339** [comment]
No, i can't add multiple `sources` values, because of how obfuscator works.

**Comment by jianweiqin** [comment]
You may ignore 'sourceMapFileName' for a directory obfuscation.

**Comment by sanex3339** [comment]
It's better to add a prefix

**Comment by sanex3339** [comment]
I reopened this issue until I add a prefix for source map names.

**Comment by sanex3339** [comment]
Released as 5.4.7
