### ISSUE TITLE
Arrow functions in classes breaks ASTParser

### ISSUE THREAD

**Issue by Kaseaa** [javascript-obfuscator/javascript-obfuscator#834]
## Expected Behavior

output: `3`

## Current Behavior

```
Error: ERROR at line 2: Unexpected token (2:8)
> ...add = (a, b) => a +...
```

## Steps to Reproduce

1. https://obfuscator.io/ (tried with npm package as well)

## Your Environment

* Obfuscator version used: 2.9.4
* Node version used: v14.0.0

# Stack trace

```
C:\Users\Administrator\Desktop\temp\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\ASTParserFacade.ts:67
        throw new Error(`ERROR at line ${position.line}: ${errorMessage}\n${formattedPointer} ${formattedCodeSlice}`);
              ^
Error: ERROR at line 2: Unexpected token (2:8)
> ...add = (a, b) => a +...
    at Function.processParsingError (C:\Users\Administrator\Desktop\temp\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\ASTParserFacade.ts:67:15)
    at Function.parse (C:\Users\Administrator\Desktop\temp\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\ASTParserFacade.ts:39:49)
    at o.parseCode (C:\Users\Administrator\Desktop\temp\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\JavaScriptObfuscator.ts:81:50)
...
```

## Minimal working example that will help to reproduce issue

```
class Test {
    add = (a, b) => a + b
}
console.log(new Test().add(1, 2));
```

**Comment by Kaseaa** [comment]
Nvm just saw this https://github.com/javascript-obfuscator/javascript-obfuscator/issues/627
