### ISSUE TITLE
reservedNames - Maximum call stack size exceeded

### ISSUE THREAD

**Issue by wxfred** [javascript-obfuscator/javascript-obfuscator#844]
I only want to obfuscate properties that end with an underscore, so my config is
```
{
    identifierNamesGenerator: 'mangled-shuffled',
    renameProperties: true,
    reservedNames: ['(?!.*_$)'],
}
```

RangeError: Maximum call stack size exceeded

ps: "javascript-obfuscator": "^2.9.4"

**Comment by sanex3339** [comment]
The error during obfuscation or during code evaluation?

**Comment by wxfred** [comment]
@sanex3339 I don't know. I just run 'npm build' in my vue cli 3 demo program. It will be fine without setting reservedNames.
Please create a vue cli 3 program, add a vue.config.js file like
```
const vueConfig = {
  configureWebpack: (config) => {
    if (process.env.NODE_ENV === 'production') {
      const WebpackObfuscator = require('webpack-obfuscator')
      config.plugins.push(new WebpackObfuscator({
        identifierNamesGenerator: 'mangled-shuffled',
        renameProperties: true,
        reservedNames: ['(?!.*_$)'],
      }, ['**/chunk-vendors.*.js']))
    }
  },
}

module.exports = vueConfig
```
then
npm install --save-dev javascript-obfuscator webpack-obfuscator@2
npm run build

```
RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at some (G:\xxx\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\AbstractIdentifierNamesGenerator.ts:64:96)
    at Array.some (<anonymous>)
    at o.notReservedName (G:\xxx\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\AbstractIdentifierNamesGenerator.ts:64:43)    
    at o.isValidIdentifierName (G:\xxx\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\AbstractIdentifierNamesGenerator.ts:44:21)
    at o.isValidIdentifierName (G:\xxx\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledIdentifierNamesGenerator.ts:88:22)
    at o.generateNewMangledName (G:\xxx\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledIdentifierNamesGenerator.ts:126:19)
    at o.generateNewMangledName (G:\xxx\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledShuffledIdentifierNamesGenerator.ts:46:22)
    at o.generateNewMangledName (G:\xxx\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledIdentifierNamesGenerator.ts:127:35)
    at o.generateNewMangledName (G:\xxx\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledShuffledIdentifierNamesGenerator.ts:46:22)
    at o.generateNewMangledName (G:\xxx\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledIdentifierNamesGenerator.ts:127:35)
    at o.generateNewMangledName (G:\xxx\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledShuffledIdentifierNamesGenerator.ts:46:22)
    at o.generateNewMangledName (G:\xxx\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledIdentifierNamesGenerator.ts:127:35)
    at o.generateNewMangledName (G:\xxx\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledShuffledIdentifierNamesGenerator.ts:46:22)
    at o.generateNewMangledName (G:\xxx\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledIdentifierNamesGenerator.ts:127:35)
    at o.generateNewMangledName (G:\xxx\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledShuffledIdentifierNamesGenerator
```

**Comment by gregbenz** [comment]
I'm seeing the same error with a slightly different use. (using  javascript-obfuscator@2.9.5)
`
options.reservedNames = ['[_A-Z*]'] //disallow properties with all caps
`

Throws error:
Message: Maximum call stack size exceeded
Details: domainThrown: true

**Comment by sanex3339** [comment]
Hi. If `renameProperties` option breaks your code - disable it.
https://github.com/javascript-obfuscator/javascript-obfuscator#i-enabled-renameproperties-option-and-my-code-broke-what-to-do

**Comment by gregbenz** [comment]
If a fix for the exclude list on properties isn't viable, what about an option to run the renaming on the basis of an include list? Relatively simple to generate a list of important properties/methods, but not a simple matter of search and replace as the target needs to be a variable or property, not a blind replace (ie, need to use a tokenized approach).

**Comment by wxfred** [comment]
@sanex3339 **renameProperties** option didn't break my code. If I set reversedNames to ['_$'], I can build the program successfully with properties that end with an underscore not be obfuscated.

@gregbenz Yeah, adding a new option like **includeName** would be nice. And I find a workaround, using terser for property renaming then using javascript-obfuscator for the others.
```
  configureWebpack: (config) => {
    if (process.env.NODE_ENV === 'production') {
      const TerserPlugin = require('terser-webpack-plugin')
      config.plugins.push(new TerserPlugin({
        exclude: /.*chunk-vendors.*.js$/,
        terserOptions: {
          mangle: {
            properties: {
              regex: /_$/,
            }
          },
        },
      }))
      const WebpackObfuscator = require('webpack-obfuscator')
      config.plugins.push(new WebpackObfuscator({
        identifierNamesGenerator: 'mangled-shuffled',
        //renameProperties: true,
        //reservedNames: ['(?!.*_$)'],
      }, ['**/chunk-vendors.*.js']))
    }
  }
```
Hope the bug can be fixed or a new include option can be added, so that I can only use this package to reduce building time.

**Comment by gregbenz** [comment]
@wxfred Thank you for the suggestion, I'll check that out.
