### ISSUE TITLE
Instant crash

### ISSUE THREAD

**Issue by Damenspike** [javascript-obfuscator/javascript-obfuscator#851]
Im getting this fatal error when trying to obfuscate the following:
`console.log('test');`

Error:
`/home/marcopolo/p3dpackager/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/ASTParserFacade.ts:67
        throw new Error(`ERROR at line ${position.line}: ${errorMessage}\n${formattedPointer} ${formattedCodeSlice}`);
              ^
Error: ERROR at line 19: Unexpected token (19:5)
> ...}comparisonExpre...
    at Function.processParsingError (/home/marcopolo/p3dpackager/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/ASTParserFacade.ts:67:15)
    at Function.parse (/home/marcopolo/p3dpackager/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/ASTParserFacade.ts:39:49)
    at Function.convertCodeToStructure (/home/marcopolo/p3dpackager/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/node/NodeUtils.ts:41:61)
    at b.apply (/home/marcopolo/p3dpackager/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/custom-code-helpers/string-array/StringArrayRotateFunctionCodeHelper.ts:38:38)
    at b.getNodeStructure (/home/marcopolo/p3dpackager/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/decorators/Initializable.ts:61:39)
    at b.getNode (/home/marcopolo/p3dpackager/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/custom-code-helpers/AbstractCustomCodeHelper.ts:38:83)
    at o.getStringArrayRotateFunctionNode (/home/marcopolo/p3dpackager/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/node-transformers/string-array-transformers/StringArrayRotateFunctionTransformer.ts:144:52)
    at o.transformNode (/home/marcopolo/p3dpackager/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/node-transformers/string-array-transformers/StringArrayRotateFunctionTransformer.ts:101:52)
    at visitorFunction (/home/marcopolo/p3dpackager/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/node-transformers/string-array-transformers/StringArrayRotateFunctionTransformer.ts:93:37)
    at Controller.<anonymous> (/home/marcopolo/p3dpackager/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/node-transformers/NodeTransformersRunner.ts:105:39)`

No matter what I try to obfuscate, unless its just a lone word or number like `1` `test`, it will just crash.

I re-installed NodeJS 14.x and re-installed the module many times. Problem persists. Im stumped

**Comment by sanex3339** [comment]
Seems your code is not a valid js code. Can you show a simple javascript file with this error?

**Comment by sanex3339** [comment]
Also please show your obfuscator options

**Comment by sanex3339** [comment]
Cannot reproduce. I did a fresh install on a different laptop and it works fine.
If possible, may you create a standalone repository with this error?

**Comment by Damenspike** [comment]
You can't replicate it for good reason. It turned out to be the stupidest thing. I had an unnecessary old String.prototype.replace function in one of the scripts which broke it.

**Comment by sanex3339** [comment]
Nice! Seems you're using the latest version. Let me know if you find other bugs in it when `rotateStringArray` option is enabled

**Comment by Damenspike** [comment]
Ok thanks fella
