### ISSUE TITLE
Ignore files / directories?

### ISSUE THREAD

**Issue by maka-io** [javascript-obfuscator/javascript-obfuscator#856]
First off, great project, thank you!

I'm trying to prevent obfuscation of a directory because the javascript-obfuscatory is erring on unexpected tokens.  I'm sure it's the nature of the files that are being obfuscated, and that's fine.  I tried adding:

`/* javascript-obfuscator:disable */`

However, the obfuscation process still seems to at least be reading the files (even though they aren't being obfuscated) and therefore still throwing an error.  So my question is:

Is it possible to actively ignore a file or, better yet, an entire directory?

For reference, this is the error:
```
/Users/mjc/.nvm/versions/node/v12.18.4/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/ASTParserFacade.ts:56
            throw new Error(errorMessage);
                  ^
Error: Unexpected token (3:0)
    at Function.processParsingError (/Users/mjc/.nvm/versions/node/v12.18.4/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/ASTParserFacade.ts:56:19)
    at Function.parse (/Users/mjc/.nvm/versions/node/v12.18.4/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/ASTParserFacade.ts:39:49)
    at o.parseCode (/Users/mjc/.nvm/versions/node/v12.18.4/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/JavaScriptObfuscator.ts:81:50)
    at obfuscate (/Users/mjc/.nvm/versions/node/v12.18.4/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/JavaScriptObfuscator.ts:72:30)
    at Function.obfuscate (/Users/mjc/.nvm/versions/node/v12.18.4/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/JavaScriptObfuscatorFacade.ts:16:53)
    at P.apply (/Users/mjc/.nvm/versions/node/v12.18.4/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/cli/JavaScriptObfuscatorCLI.ts:197:82)
    at P.processSourceCodeWithoutSourceMap (/Users/mjc/.nvm/versions/node/v12.18.4/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/decorators/Initializable.ts:61:39)
    at P.apply (/Users/mjc/.nvm/versions/node/v12.18.4/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/cli/JavaScriptObfuscatorCLI.ts:193:18)
    at P.processSourceCode (/Users/mjc/.nvm/versions/node/v12.18.4/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/decorators/Initializable.ts:61:39)
    at /Users/mjc/.nvm/versions/node/v12.18.4/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/cli/JavaScriptObfuscatorCLI.ts:177:22
```
Thanks

**Comment by sanex3339** [comment]
Hi. You can use `--exclude` option
https://github.com/javascript-obfuscator/javascript-obfuscator#cli-options

**Comment by maka-io** [comment]
Hey @sanex3339 , 
Thanks for the reply.  I gave that a shot, but no dice.  

`javascript-obfuscator ./lib --exclude=./lib/templates/ --output ./lib-o --config=obfuscator.json`

still results in:
```/Users/mjc/.nvm/versions/node/v12.18.4/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/ASTParserFacade.ts:56
            throw new Error(errorMessage);```

**Comment by sanex3339** [comment]
`exclude` option accepts `glob` syntax. Try something like:
```
--exclude='./lib/templates/**/**'
```

**Comment by maka-io** [comment]
It still trying to take a peek into that directory:

```
[javascript-obfuscator-cli] Error in file: lib/templates/api/api.js... 

/Users/mjc/.nvm/versions/node/v12.18.4/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/ASTParserFacade.ts:56
            throw new Error(errorMessage);
                  ^
Error: Unexpected token (2:0)
    at Function.processParsingError (/Users/mjc/.nvm/versions/node/v12.18.4/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/ASTParserFacade.ts:56:19)
    at Function.parse (/Users/mjc/.nvm/versions/node/v12.18.4/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/ASTParserFacade.ts:39:49)
    at o.parseCode (/Users/mjc/.nvm/versions/node/v12.18.4/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/JavaScriptObfuscator.ts:81:50)
    at obfuscate (/Users/mjc/.nvm/versions/node/v12.18.4/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/JavaScriptObfuscator.ts:72:30)
    at Function.obfuscate (/Users/mjc/.nvm/versions/node/v12.18.4/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/JavaScriptObfuscatorFacade.ts:16:53)
    at P.apply (/Users/mjc/.nvm/versions/node/v12.18.4/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/cli/JavaScriptObfuscatorCLI.ts:197:82)
    at P.processSourceCodeWithoutSourceMap (/Users/mjc/.nvm/versions/node/v12.18.4/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/decorators/Initializable.ts:61:39)
    at P.apply (/Users/mjc/.nvm/versions/node/v12.18.4/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/cli/JavaScriptObfuscatorCLI.ts:193:18)
    at P.processSourceCode (/Users/mjc/.nvm/versions/node/v12.18.4/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/decorators/Initializable.ts:61:39)
    at /Users/mjc/.nvm/versions/node/v12.18.4/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/cli/JavaScriptObfuscatorCLI.ts:177:22
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! `javascript-obfuscator ./lib --exclude='./lib/templates/**/**' --output ./lib-o --config=obfuscator.json`
```

**Comment by sanex3339** [comment]
Show me the content of that file please.

**Comment by maka-io** [comment]
Shouldn't the contents of the file not matter if it's being excluded?

**Comment by sanex3339** [comment]
Yes. If a file is excluded - it should not be produced by the obfuscator.
I just interested in this error:
```
throw new Error(errorMessage);
```
Want to understand why it's happening.

About your glob. Try this: `issue-856/lib/templates/**/**` without `./` characters at the start. I tested and it works

**Comment by sanex3339** [comment]
I tested it here:
https://www.digitalocean.com/community/tools/glob?comments=true&glob=issue-856%2Flib%2Ftemplates%2F%2A%2A%2F%2A%2A&matches=false&tests=foo%2Fissue-856%2Flib%2Ftemplates%2Ffile-b.js%20

**Comment by maka-io** [comment]
Gotcha, here is the contents of that file:
```
import { Meteor } from 'meteor/meteor';
<% if (api === 'rest') { %>import { Restivus } from 'meteor/maka:rest';<% } else { %>import { Restivus } from 'meteor/nimble:restivus';<% } %>
import <%= name %> from './<%= fileName %>-collection';
```

And your notation indeed works, thanks!!!

**Comment by sanex3339** [comment]
Nice!
