### ISSUE TITLE
Unexpected character '#'

### ISSUE THREAD

**Issue by botboi37** [javascript-obfuscator/javascript-obfuscator#867]
## Expected Behavior
The obfuscator should not complain about declaring private members. Please correct me if I am wrong though, since private members are not standardized or are they?

## Current Behavior
When trying to declare a private field/method in a class, the obfuscator throws an error about an unexpected character '#'.
`Error: ERROR at line x: Unexpected character '#' (x:y)`

## Steps to Reproduce
1. Make a class and declare a private field/method (begins with #). Can be static or non static.
2. Try to obfuscate the code.

## Your Environment
I have nodejs v14 and private fields/methods have been supported since v12 so this is definitely not an unexpected character.
* Obfuscator version used: 2.10.3
* Node version used: 14.15.4

# Stack trace
node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\ASTParserFacade.ts:67
        throw new Error(`ERROR at line ${position.line}: ${errorMessage}\n${formattedPointer} ${formattedCodeSlice}`);
              ^
Error: ERROR at line 939: Unexpected character '#' (939:11)
> ...static #newRID() {...
    at Function.processParsingError (node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\ASTParserFacade.ts:67:15)
    at Function.parse (node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\ASTParserFacade.ts:39:49)
    at o.parseCode (node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\JavaScriptObfuscator.ts:81:50)
    at obfuscate (node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\JavaScriptObfuscator.ts:72:30)
    at Function.obfuscate (node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\JavaScriptObfuscatorFacade.ts:16:53)
    at Object.<anonymous> (obfuscate.js:17:25)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)

## Minimal working example that will help to reproduce issue
```js
class A {
   #a;
   static #b;
   #c() { };
   static #d() { };
} // Any of these declarations will lead to an error.
```

**Comment by sanex3339** [comment]
Hi. Obfuscator supports only stage4 features that are supported by escodegen and acorn packages.

**Comment by botboi37** [comment]
Ok, thank you
