### ISSUE TITLE
How do I use sourceMap to recover the error message from the console output of Node.js ?

### ISSUE THREAD

**Issue by jianweiqin** [javascript-obfuscator/javascript-obfuscator#870]
How do I use sourceMap to recover the error message below from the console output of Node.js ?

>TypeError: _0x4cc098[(_0x1a48a1(...) + _0x1a48a1(...) + "e")] is not a function
>    at /path/to/file.js:1:32015

**Comment by sanex3339** [comment]
You should enable `sourceMap` option. Also, it depends on your other build tools.

**Comment by sanex3339** [comment]
Did i help you?

**Comment by jianweiqin** [comment]
No. I meant I didn't know where the error happened from the obfuscated output. 
example:
Running the obfuscated js file will get the output:
>TypeError: _0x4cc098[(_0x1a48a1(...) + _0x1a48a1(...) + "e")] is not a function
>at /path/to/file.js:1:32015

**I know nothing from the obfuscated error message output.**
how do i recover it to the original:
>TypeError: a.toLowerCase is not a function
>at /path/to/file.js:10:22

**I need to know the line and the col of the original file, and what '_0x4cc098[(_0x1a48a1(...) + _0x1a48a1(...) + "e")]' means**
Thank you!

**Comment by sanex3339** [comment]
As i said before, you have to enable `sourceMap` option. If the error happens in the obfuscated part of the original code it should help. 

But if the error happens after obfuscation in the additional code that was added during obfuscation, `sourceMap` won't help, and the error is probably a bug in the obfuscator, so I have to fix it

**Comment by jianweiqin** [comment]
I have enabled sourceMap option and got the .js.map file, but won't help.
![3](https://user-images.githubusercontent.com/26958373/106857724-7c1c8380-66fb-11eb-9097-4aefa816a69c.png)

 I only got the output below:
![1](https://user-images.githubusercontent.com/26958373/106856927-3d39fe00-66fa-11eb-8804-f4f771e0afe9.png)

If I run the original file, will get:
![2](https://user-images.githubusercontent.com/26958373/106857059-72dee700-66fa-11eb-960f-4ce728937be5.png)
so I can locate where the error happened.
But from the obfuscated output, I can't.

**Comment by sanex3339** [comment]
Hmm. I will investigate this.
