### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by wxfred** [javascript-obfuscator/javascript-obfuscator#881]
Please try the simple options below,
```
options: {
  identifierNamesGenerator: 'mangled-shuffled',
  reservedNames: ['.*'],
}
```

Obfuscator version used: 2.9.4

Stack trace
```
RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at o.isValidIdentifierName (G:\XXX\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledIdentifierNamesGenerator.ts:87:5)
    at o.generateNewMangledName (G:\XXX\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledIdentifierNamesGenerator.ts:126:19)
    at o.generateNewMangledName (G:\XXX\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledShuffledIdentifierNamesGenerator.ts:46:22)
    at o.generateNewMangledName (G:\XXX\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledIdentifierNamesGenerator.ts:127:35)
    at o.generateNewMangledName (G:\XXX\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledShuffledIdentifierNamesGenerator.ts:46:22)
    at o.generateNewMangledName (G:\XXX\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledIdentifierNamesGenerator.ts:127:35)
    at o.generateNewMangledName (G:\XXX\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledShuffledIdentifierNamesGenerator.ts:46:22)
    at o.generateNewMangledName (G:\XXX\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledIdentifierNamesGenerator.ts:127:35)
    at o.generateNewMangledName (G:\XXX\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledShuffledIdentifierNamesGenerator.ts:46:22)
    at o.generateNewMangledName (G:\XXX\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledIdentifierNamesGenerator.ts:127:35)
    at o.generateNewMangledName (G:\XXX\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledShuffledIdentifierNamesGenerator.ts:46:22)
    at o.generateNewMangledName (G:\XXX\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledIdentifierNamesGenerator.ts:127:35)
    at o.generateNewMangledName (G:\XXX\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledShuffledIdentifierNamesGenerator.ts:46:22)
    at o.generateNewMangledName (G:\XXX\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledIdentifierNamesGenerator.ts:127:35)
    at o.generateNewMangledName (G:\XXX\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledShuffledIdentifierNamesGenerator.ts:46:22)
    at o.generateNewMangledName (G:\XXX\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\generators\identifier-names-generators\MangledIdentifierNamesGenerator.ts:127:35)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! temten@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
```

In `src/generators/identifier-names-generators/MangledIdentifierNamesGenerators.ts` line 231, function `isValidIdentifierName` (which is in `src/generators/identifier-names-generators/AbstractIdentifierNamesGenerators.ts`) excludes new mangled names that are matched with `reservedNames`. I think that's the problem.
```
// src/generators/identifier-names-generators/MangledIdentifierNamesGenerators.ts
protected generateNewMangledName (previousMangledName: string): string {
  ...
  if (!this.isValidIdentifierName(newMangledName)) {
    newMangledName = this.generateNewMangledName(newMangledName);
  }

  return newMangledName;
}

// src/generators/identifier-names-generators/AbstractIdentifierNamesGenerators.ts
public isValidIdentifierName (name: string): boolean {
  return this.notReservedName(name) && !this.preservedNamesSet.has(name);
}

private notReservedName (name: string): boolean {
  return this.options.reservedNames.length
    ? !this.options.reservedNames.some((reservedName: string) =>
      new RegExp(reservedName, 'g').exec(name) !== null
    )
    : true;
}
```

In the document, `reservedNames` means something should not be obfuscated, in my case, `.*` means everything, then when you generate mangled names, you use `reservedNames` again for excluding, every mangled name will be excluded, it causes the dead loop.

**Comment by da411d** [comment]
I faced same issue when used regex in reservedNames.
But i used something like `"\\$\\$"` as i remember

**Comment by Androbin** [comment]
I am facing the same issue with default settings and this input:
```js
class Foo {
    foo;
}
```

**Comment by sanex3339** [comment]
@Androbin this is absolutely different thing. Class properties support will be added in this PR:
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/916

Issue: https://github.com/javascript-obfuscator/javascript-obfuscator/issues/909

**Comment by gevinduM** [comment]
> I am facing the same issue with default settings and this input:
> 
> ```js
> class Foo {
>     foo;
> }
> ```

were you able to solve this ?

**Comment by sanex3339** [comment]
Hi. We have to wait until eslint/eslint-scope#71 will be merged

**Comment by regnaio** [comment]
@sanex3339 Sorry to bother, and thank you for all of your time and help

I cloned your repo locally, merged https://github.com/javascript-obfuscator/javascript-obfuscator/pull/916 with `master`, and rebuilt `index.browser.js`

(I also had to add `globalObject: 'this'` to `module.exports.output` in `webpack.browser.js` due to running into the error: https://stackoverflow.com/questions/64639839/typescript-webpack-library-generates-referenceerror-self-is-not-defined)

I then tried obfuscating a JS file with classes with properties, and still ran into `RangeError: Maximum call stack size exceeded`. I removed the class properties and the obfuscation ran successfully.

Would you expect obfuscation to fail even with my local attempt to merge https://github.com/javascript-obfuscator/javascript-obfuscator/pull/916 with `master`?

Thank you, sanex3339!

**Comment by sanex3339** [comment]
Please wait until the official support. Even after eslint/eslint-scope#71 i will update this branch.

**Comment by gevinduM** [comment]
> Please wait until the official support. Even after [eslint/eslint-scope#71](https://github.com/eslint/eslint-scope/pull/71) i will update #916 branch.

will this fix Class properties support  as well?

**Comment by sanex3339** [comment]
With the next `eslint-scope` release i will continue to add class properties support to the obfuscator

**Comment by gevinduM** [comment]
> eslint/eslint-scope#71

its merged ✌️

**Comment by sanex3339** [comment]
Yes. But the release date of `eslint-scope` is still unknown.

**Comment by Androbin** [comment]
@sanex3339 eslint/eslint-scope#71 was released in [v6.0.0](https://github.com/eslint/eslint-scope/releases/tag/v6.0.0)

**Comment by regnaio** [comment]
Just tried out sanex3339's merge of #916! Seems to work perfectly for classes 😄

**Comment by qozle** [comment]
Has this been fixed for the initial regex problem that this issue was opened for?  I'm getting `RangeError: Maximum call stack size exceeded` when using the grunt obfuscator plugin.  Here's my JS:

```
$(async () => {

	var d = new $.Deferred();

	$.ajax({
		url: "/customers",
		method: "GET",
		headers: {
			"App-Source": "FLEX DB Web Reader"
		},
		success: (res) => {
			console.log("We got a response: ", res);
			d.resolve(res);
		},
		error: (err) => {
			d.reject(err);
		}
	});

	var rawData = await d;
	
	$("#gridContainer").dxDataGrid({
		dataSource: rawData,
		loadMode: "raw",
		sorting: { mode: "single" },
		filterRow: { visible: true },
		searchPanel: {
			visible: true,
			highlightCaseSensitive: true,
		},
		groupPanel: { visible: true },
		paging: { pageSize: 10 },
		pager: {
			showPageSizeSelector: true,
			allowedPageSizes: [10, 25, 50, 100],
		},
		allowColumnReordering: true,
		rowAlternationEnabled: true,
		showBorders: true,
		columns: [
			{
				dataField: "name",
				caption: "Customer Name",
			},
			{
				dataField: "addr1",
				caption: "Address Line 1",
			},
			{
				dataField: "addr2",
				caption: "Address Line 2",
			},
			{
				dataField: "city",
				caption: "City",
			},
			{
				dataField: "state",
				caption: "State",
			},
			{
				dataField: "zip",
				caption: "Postal / Zip code",
			},
			{
				dataField: "country",
				caption: "Country",
			},
			{
				dataField: "phone",
				caption: "Phone",
			},
			{
				dataField: "email",
				caption: "E-mail",
			}
		],
	});
});
```

And I'm using these options:

```
options: {
    renamePropertiesMode: 'safe',
    selfDefend: false,
    reservedNames: ["\$.*"],
    reservedStrings: ["\$\."]
}
```

This is part of a different issue- when I use the default options, the code won't run because I get this error:

```
Uncaught TypeError: $[_0x283738(...)] is not a function
```

Which is pointing to here:

```
 $(async()=>{
                var _0x283738 = _0x5a53
                  , _0x586abb = new $[(_0x283738(0x194))]();
                $[_0x283738(0x18f)]({  //  this line here is where the error is raised from
                    'url': _0x283738(0x192),
                    'method': _0x283738(0x17f),
                    'headers': {
                        'App-Source': _0x283738(0x197)
... et c
```

**Comment by sanex3339** [comment]
Will be fixed in 5.4.0 later today
