### ISSUE TITLE
throw new ReferenceError(`Cannot open config file with path: ${configPath}`);

### ISSUE THREAD

**Issue by Yuri2** [javascript-obfuscator/javascript-obfuscator#902]
cdm: javascript-obfuscator 12.js --config 123.json --output 123.js

ReferenceError: Cannot open config file with path: C:\Users\ajie\Desktop\123js\text.json
    at Function.getUserConfig (C:\Users\ajie\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\cli\utils\CLIUtils.ts:41:23)
    at Function.buildOptions (C:\Users\ajie\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\cli\JavaScriptObfuscatorCLI.ts:64:76)
    at j.apply (C:\Users\ajie\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\cli\JavaScriptObfuscatorCLI.ts:84:56)
    at j.apply (C:\Users\ajie\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\decorators\Initializable.ts:73:43)
    at j.apply (C:\Users\ajie\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\decorators\Initializable.ts:73:43)
    at j.apply (C:\Users\ajie\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\decorators\Initializable.ts:73:43)
    at j.apply (C:\Users\ajie\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\decorators\Initializable.ts:73:43)
    at j.initialize (C:\Users\ajie\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\decorators\Initializable.ts:73:43)
    at Function.obfuscate (C:\Users\ajie\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\JavaScriptObfuscatorCLIFacade.ts:9:33)

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Obfuscator version used:
* Node version used:

# Stack trace

**Comment by Yuri2** [comment]
没事了，重启了一下就可以了

**Comment by sanex3339** [comment]
Please use English language here.

**Comment by sanex3339** [comment]
Hi. Please provide more info.

**Comment by sanex3339** [comment]
Closed as old. Feel free to write here or create a new issue with more details
