### ISSUE TITLE
Rare "not a function" issue on Java Nashorn that may due to splitStrings

### ISSUE THREAD

**Issue by jessefjxm** [javascript-obfuscator/javascript-obfuscator#917]
## Expected Behavior
All obfuscated scripts runs as nice as original ones.

## Current Behavior
Some obfuscated scripts (around 1%) came up with a "not a function" error, while original script runs well.
![image](https://user-images.githubusercontent.com/1498592/117566430-2e902800-b0e9-11eb-9aae-64616bef136b.png)
Obfuscated codes:
![image](https://user-images.githubusercontent.com/1498592/117566441-3c45ad80-b0e9-11eb-9571-2ec73a20b581.png)
Original codes:
![image](https://user-images.githubusercontent.com/1498592/117566456-4b2c6000-b0e9-11eb-9e48-1b8953114c79.png)
Here `cm` is a Java API object, and `cm.getPlayer().getInfoQuest` guarantees a non-null string.

## Steps to Reproduce
1. Obfuscate https://pastebin.com/RLVENndG with https://pastebin.com/aB4EvDga
2. Run obfuscated script (https://pastebin.com/zTB8BZLU) from `start()` by java nashorn (https://pastebin.com/7kSpRwTF)

## Your Environment
* Obfuscator version used: 2.12.0_2021-04-10T20:28:14.418Z
* Node version used: v14.7.0
* Windows 10
* Java8_281, using nashorn engine to run JavaScript

# Stack trace
```
javax.script.ScriptException: TypeError: (cm[T(197, 163, 185, 180)]().getInfoQuest(99993))[x(177, 155, 154, 160)] is not a function in <eval> at line number 1
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
	at org.bms.scripting.manager.AbstractScriptManager.simpleCheck(AbstractScriptManager.java:108)
	at org.bms.scripting.manager.AbstractScriptManager.main(AbstractScriptManager.java:94)
Caused by: <eval>:1 TypeError: (cm[T(197, 163, 185, 180)]().getInfoQuest(99993))[x(177, 155, 154, 160)] is not a function
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.nashorn.internal.runtime.Undefined.lookup(Undefined.java:102)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:106)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:98)
	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176)
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
	at jdk.nashorn.internal.scripts.Script$Recompilation$32$4512III$\^eval\_.action(<eval>:1)
	at jdk.nashorn.internal.scripts.Script$Recompilation$31$3062$\^eval\_.start(<eval>:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
	at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
	... 3 more
```

## Minimal working example that will help to reproduce issue
1. Original script: https://pastebin.com/RLVENndG
2. Config: https://pastebin.com/aB4EvDga
3. Obfuscated script: https://pastebin.com/zTB8BZLU
4. Java test codes: https://pastebin.com/7kSpRwTF

**Comment by jessefjxm** [comment]
Did more experiments and figured out that calling non-JS string interface cause such issue. Maybe nashorn should be blamed?

**Comment by sanex3339** [comment]
This is actual?
