### ISSUE TITLE
config option fires ReferenceError

### ISSUE THREAD

**Issue by L0rdH4x0r** [javascript-obfuscator/javascript-obfuscator#950]
When calling like `javascript-obfuscator input.js --output output.js --config config.json` I get

```
CLIUtils.ts:41
                throw new ReferenceError(`Cannot open config file with path: ${configPath}`);
ReferenceError: Cannot open config file with path: C:\temp\config.json 
    at Function.getUserConfig (node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\cli\utils\CLIUtils.ts:41:23)
```

Except that good work!

**Comment by sanex3339** [comment]
Hi. Show me more info.  Your current working directory, obfuscator version.

**Comment by itaybia** [comment]
same happens to me:

command:
javascript-obfuscator /Users/X/Downloads/location_locator.js -o /Users/X/Downloads/location_locator_2.js --config /Users/X/Downloads/obfuscate_config.json

javascript-obfuscator --version
2.16.0_2021-07-16T15:46:52.517Z


config.json content (same as in the README file):
{
    compact: true,
    controlFlowFlattening: false,
    controlFlowFlatteningThreshold: 0.75,
    deadCodeInjection: false,
    deadCodeInjectionThreshold: 0.4,
    debugProtection: false,
    debugProtectionInterval: false,
    disableConsoleOutput: false,
    domainLock: [],
    domainLockRedirectUrl: 'about:blank',
    forceTransformStrings: [],
    identifierNamesCache: null,
    identifierNamesGenerator: 'hexadecimal',
    identifiersDictionary: [],
    identifiersPrefix: '',
    ignoreRequireImports: false,
    inputFileName: '',
    log: false,
    numbersToExpressions: false,
    optionsPreset: 'default',
    renameGlobals: false,
    renameProperties: false,
    renamePropertiesMode: 'safe',
    reservedNames: [],
    reservedStrings: [],
    rotateStringArray: true,
    seed: 0,
    selfDefending: false,
    shuffleStringArray: true,
    simplify: true,
    sourceMap: false,
    sourceMapBaseUrl: '',
    sourceMapFileName: '',
    sourceMapMode: 'separate',
    splitStrings: false,
    splitStringsChunkLength: 10,
    stringArray: true,
    stringArrayIndexesType: [
        'hexadecimal-number'
    ],
    stringArrayEncoding: [],
    stringArrayIndexShift: true,
    stringArrayWrappersCount: 1,
    stringArrayWrappersChainedCalls: true,
    stringArrayWrappersParametersMaxCount: 2,
    stringArrayWrappersType: 'variable',
    stringArrayThreshold: 0.75,
    target: 'browser',
    transformObjectKeys: false,
    unicodeEscapeSequence: false
}

**Comment by L0rdH4x0r** [comment]
Hmm, interestingly after testing it out some days later having rebooted some times it seemd to work. So it was only a temporary issue. Possibly another cra process kept some locks/ports or so.

I had the obfuscater v2.15.5 installed in the project folder running via node_modules\.bin\javascript-obfuscator.

For me it can be closed. Don't know if @itaybia got it fixed too?

**Comment by itaybia** [comment]
mine still happens:


/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/cli/utils/CLIUtils.ts:41
                throw new ReferenceError(`Cannot open config file with path: ${configPath}`);
                      ^
ReferenceError: Cannot open config file with path: /Users/itaybianco/Downloads/obfuscate_config.json
    at Function.getUserConfig (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/cli/utils/CLIUtils.ts:41:23)
    at Function.buildOptions (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/cli/JavaScriptObfuscatorCLI.ts:65:76)
    at G.apply (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/cli/JavaScriptObfuscatorCLI.ts:89:56)
    at G.apply (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/decorators/Initializable.ts:79:43)
    at G.apply (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/decorators/Initializable.ts:79:43)
    at G.apply (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/decorators/Initializable.ts:79:43)
    at G.apply (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/decorators/Initializable.ts:79:43)
    at G.apply (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/decorators/Initializable.ts:79:43)
    at G.initialize (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/decorators/Initializable.ts:79:43)
    at Function.obfuscate (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/JavaScriptObfuscatorCLIFacade.ts:9:33)

**Comment by sanex3339** [comment]
@itaybia please show me your obfuscator command

**Comment by itaybia** [comment]
@sanex3339 i wrote it in my first comment above with the config that i used.

**Comment by haninaguib** [comment]
I am also getting this error. version 4.0.0_2022-02-14T16:47:01.077Z
I am on Mac OSX 12.3.1
Command used
`javascript-obfuscator --config ./etc/obs/obs.js src/main/webapp/WEB-INF/templates/js --output src/main/webapp/WEB-INF/templates/obfuscated
`

The config file is a copy of the "High obfuscation, low performance" found on the README.md
```
{
    compact: true,
    controlFlowFlattening: true,
    controlFlowFlatteningThreshold: 1,
    deadCodeInjection: true,
    deadCodeInjectionThreshold: 1,
    debugProtection: true,
    debugProtectionInterval: 4000,
    disableConsoleOutput: true,
    identifierNamesGenerator: 'hexadecimal',
    log: false,
    numbersToExpressions: true,
    renameGlobals: false,
    selfDefending: true,
    simplify: true,
    splitStrings: true,
    splitStringsChunkLength: 5,
    stringArray: true,
    stringArrayCallsTransform: true,
    stringArrayEncoding: ['rc4'],
    stringArrayIndexShift: true,
    stringArrayRotate: true,
    stringArrayShuffle: true,
    stringArrayWrappersCount: 5,
    stringArrayWrappersChainedCalls: true,    
    stringArrayWrappersParametersMaxCount: 5,
    stringArrayWrappersType: 'function',
    stringArrayThreshold: 1,
    transformObjectKeys: true,
    unicodeEscapeSequence: false
}

```

The error I get

```
/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/cli/utils/CLIUtils.ts:41
                throw new ReferenceError(`Cannot open config file with path: ${configPath}`);
                      ^
ReferenceError: Cannot open config file with path: /Users/haninaguib/Projects/rostami-magic/inject-3/inject3-server/etc/obs/obs.js
    at Function.getUserConfig (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/cli/utils/CLIUtils.ts:41:23)
    at Function.buildOptions (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/cli/JavaScriptObfuscatorCLI.ts:66:76)
    at L.apply (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/cli/JavaScriptObfuscatorCLI.ts:90:56)
    at L.apply (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/decorators/Initializable.ts:80:43)
    at L.apply (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/decorators/Initializable.ts:80:43)
    at L.apply (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/decorators/Initializable.ts:80:43)
    at L.apply (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/decorators/Initializable.ts:80:43)
    at L.apply (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/decorators/Initializable.ts:80:43)
    at L.initialize (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/decorators/Initializable.ts:80:43)
    at Function.obfuscate (/usr/local/lib/node_modules/javascript-obfuscator/dist/webpack:/javascript-obfuscator/src/JavaScriptObfuscatorCLIFacade.ts:9:33)


```
