### ISSUE TITLE
Unable to Obfuscate EJS Template

### ISSUE THREAD

**Issue by Zarmeena** [javascript-obfuscator/javascript-obfuscator#975]
## Expected Behavior

The input JS file should be obfuscated

module.exports.config = {
    specs: [
	 <% if(var=='A') { %>
        'Hello'
	 <% } else { %>
		'Hi'
	 <% } %>
    ]
} 

## Current Behavior
The code in test.js should be obfuscated and print the console log
[test.zip](https://github.com/javascript-obfuscator/javascript-obfuscator/files/6924590/test.zip)

## Steps to Reproduce

1. Execute 'node test.js' command for the attached file

## Your Environment

* Obfuscator version used: ^2.18.1
* Node version used: v12.21.0

# Stack trace

## Minimal working example that will help to reproduce issue
 Error: ERROR at line 3: Unexpected token (3:2)
> ...<% if(var=='A')...
    at Function.processParsingError (C:\Test\JS Obfuscation\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\ASTParserFacade.ts:73:15)
    at Function.parse (C:\Backup_Zarmina\Retail\Artifacts\Chauffeur\JS Obfuscation\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\ASTParserFacade.ts:39:49)
    at o.parseCode (C:\Backup_Zarmina\Retail\Artifacts\Chauffeur\JS Obfuscation\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\JavaScriptObfuscator.ts:82:50)
    at obfuscate (C:\Backup_Zarmina\Retail\Artifacts\Chauffeur\JS Obfuscation\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\JavaScriptObfuscator.ts:73:30)
    at Function.obfuscate (C:\Backup_Zarmina\Retail\Artifacts\Chauffeur\JS Obfuscation\node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\JavaScriptObfuscatorFacade.ts:16:56)
    at Object.<anonymous> (C:\Backup_Zarmina\Retail\Artifacts\Chauffeur\JS Obfuscation\test.js:3:46)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

**Comment by sanex3339** [comment]
Hi. This is not a valid javascript code. Obfuscator supports only valid javascript code
